@_exported import SkyBridgeAppleTransport

public typealias NativeWebSocketCallbacks = SkyBridgeAppleTransport.NativeWebSocketCallbacks
public typealias NativeWebSocketClient = SkyBridgeAppleTransport.NativeWebSocketClient
public typealias WebSocketSignalingClient = SkyBridgeAppleTransport.WebSocketSignalingClient
