use clap::Parser;

use crate::Cli;

#[test]
fn smoke_subcommands_parse_with_json_flags() {
    assert!(
        Cli::try_parse_from([
            "skybridge",
            "smoke",
            "webrtc",
            "gate",
            "--session-id",
            "SESSION1",
            "--artifact-dir",
            "/tmp",
            "--timeout-seconds",
            "240",
            "--min-pass-seconds",
            "60",
            "--poll-interval-seconds",
            "2",
            "--min-fps",
            "30.00",
            "--require-audio",
            "true",
            "--json",
        ])
        .is_ok()
    );
    assert!(
        Cli::try_parse_from([
            "skybridge",
            "smoke",
            "suite",
            "--profile",
            "all",
            "--skip-real-device",
            "--soak-seconds",
            "600",
            "--timeout-seconds",
            "900",
            "--dry-run",
            "--json",
        ])
        .is_ok()
    );
    assert!(Cli::try_parse_from(["skybridge", "smoke", "faults", "--dry-run", "--json"]).is_ok());
    assert!(
        Cli::try_parse_from([
            "skybridge",
            "smoke",
            "fault-detection",
            "--dry-run",
            "--json"
        ])
        .is_ok()
    );
    assert!(
        Cli::try_parse_from([
            "skybridge",
            "smoke",
            "faults",
            "--iterations",
            "200",
            "--timeout-ms",
            "2500",
            "--delay-ms",
            "200",
            "--progress-interval",
            "50",
            "--dry-run",
            "--json",
        ])
        .is_ok()
    );
    assert!(
        Cli::try_parse_from([
            "skybridge",
            "smoke",
            "local-webrtc",
            "--min-fps",
            "30",
            "--mainstream-resolutions",
            "--dry-run",
            "--json",
        ])
        .is_ok()
    );
    assert!(
        Cli::try_parse_from([
            "skybridge",
            "smoke",
            "local-p2p",
            "--scenario",
            "compat-pure-pqc",
            "--rounds",
            "2",
            "--timeout-seconds",
            "180",
            "--dry-run",
            "--json",
        ])
        .is_ok()
    );
    assert!(
        Cli::try_parse_from([
            "skybridge",
            "smoke",
            "real-device",
            "--real-device-id",
            "00008132-0006452C1138801C",
            "--min-fps",
            "30",
            "--dry-run",
            "--json",
        ])
        .is_ok()
    );
    assert!(
        Cli::try_parse_from([
            "skybridge",
            "smoke",
            "real-device",
            "--video-size",
            "1728x1117",
            "--video-size",
            "2056x1329",
            "--dry-run",
            "--json",
        ])
        .is_ok()
    );
    assert!(
        Cli::try_parse_from([
            "skybridge",
            "smoke",
            "all",
            "--skip-real-device",
            "--dry-run",
            "--json",
        ])
        .is_ok()
    );
    for profile in [
        "script-tests",
        "ios-config",
        "local-p2p",
        "local-webrtc",
        "benchmarks",
    ] {
        assert!(
            Cli::try_parse_from([
                "skybridge",
                "smoke",
                "suite",
                "--profile",
                profile,
                "--dry-run",
                "--json",
            ])
            .is_ok(),
            "profile {profile} should parse"
        );
    }
}
