// Generated by Scripts/generate_visual_parity_assets.py. Do not edit by hand.
namespace Skybridge.WinClient.VisualParity;

internal static class GeneratedVisualParity
{
    internal static class Layout
    {
        public const double CaptureWidth = 1200;
        public const double CaptureHeight = 800;
        public const double WindowWidth = 1200;
        public const double WindowHeight = 800;
        public const double ShellOuterMargin = 26;
        public const double ShellSurfacePadding = 12;
        public const double ShellCornerRadius = 30;
        public const double SidebarWidth = 246;
        public const double SidebarPadding = 18;
        public const double SidebarCornerRadius = 24;
        public const double TopBarHeight = 56;
        public const double TopBarCornerRadius = 18;
        public const double PanelCornerRadius = 22;
        public const double SubtlePanelCornerRadius = 20;
        public const double MetricCardCornerRadius = 18;
        public const double CardInset = 18;
        public const double NavButtonCornerRadius = 12;
        public const double NavButtonHeight = 36;
        public const double ContentGap = 16;
        public const double ContentHorizontalPadding = 24;
        public const double StatusChipHeight = 30;
        public const double ChipCornerRadius = 999;
        public const double LoginCardWidth = 354;
        public const double LoginCardCornerRadius = 20;
        public const double LoginSegmentHeight = 34;
        public const double ButtonHeight = 38;
        public const double IconButtonSize = 34;
    }

    internal static class Materials
    {
        public const double DefaultGlassOpacity = 0.8;
        public const double DefaultBackgroundIntensity = 1.0;
        public const double CardFillAlphaDark = 0.13;
        public const double CardFillAlphaLight = 0.24;
        public const double CardStrokeAlpha = 0.1;
        public const double ShellSurfaceFillAlphaDark = 0.16;
        public const double ShellSurfaceFillAlphaLight = 0.42;
        public const double ShellSurfaceStrokeAlpha = 0.16;
        public const double TopBarFillAlphaDark = 0.55;
    }

    internal static class Motion
    {
        public const double EaseDuration = 0.3;
        public const double HoverDuration = 0.2;
        public const double PressDuration = 0.05;
        public const double SpringResponse = 0.4;
        public const double SpringDampingFraction = 0.9;
    }

    internal static class Typography
    {
        public const double HeroTitleSize = 30;
        public const double SectionTitleSize = 20;
        public const double BodyTextSize = 13;
        public const double CaptionTextSize = 11;
        public const double NavTitleSize = 15;
        public const double NavSubtitleSize = 10;
        public const double PageTitleSize = 16;
        public const double PageSubtitleSize = 12;
        public const double LoginHeroTitleSize = 28;
        public const double LoginSectionTitleSize = 22;
        public const double ButtonTextSize = 14;
    }

    internal static class Palette
    {
        public static readonly string[] WindowGradientDark = new[] { "#3B4F78", "#6F87B3", "#C4CEE3" };
        public static readonly string[] WindowGradientLight = new[] { "#FFFFFF", "#F0F4FC" };
        public const string SidebarBackground = "#2E3857F0";
        public const string ShellSurfaceFill = "#29FFFFFF";
        public const string ShellSurfaceStroke = "#29FFFFFF";
        public const string TopBarFill = "#8C47618F";
        public const string PanelFillDark = "#21FFFFFF";
        public const string PanelFillLight = "#3DFFFFFF";
        public const string PanelStroke = "#1AFFFFFF";
        public const string MetricCardFillDark = "#24FFFFFF";
        public const string MetricCardFillLight = "#42FFFFFF";
        public const string RowFillDark = "#24000000";
        public const string LoginCardFill = "#E0FFFFFF";
        public const string LoginCardStroke = "#10000000";
        public const string InputFillLight = "#14000000";
        public const string Accent = "#D93072EF";
        public const string AccentPressed = "#D8205ED6";
        public const string Success = "#FF4DC770";
        public const string Warning = "#FFFF9A4D";
        public const string Danger = "#FFFF5C5C";
        public const string TextPrimaryDark = "#FFF7FAFF";
        public const string TextSecondaryDark = "#B8FFFFFF";
        public const string TextMutedDark = "#75FFFFFF";
        public const string TextPrimaryLight = "#C7000000";
        public const string TextSecondaryLight = "#6B000000";
        public const string TextMutedLight = "#47000000";
        public const string SelectedNavFill = "#D12368E0";
        public const string SelectedNavIndicator = "#FFFFFFFF";
    }

    internal static class Navigation
    {
        public static readonly string[] PrimaryOrder = new[] { "dashboard", "devices", "usb", "transfers", "remote", "monitor", "settings" };
        public static readonly string[] SecondaryOrder = new[] { "recent", "profile", "login" };
    }
}
