pub(super) const SOURCE_FRAGMENTS: &[(&str, &str)] = &[
    ("check_coverage.rs", include_str!("../../check_coverage.rs")),
    (
        "check_coverage/entries.rs",
        include_str!("../../check_coverage/entries.rs"),
    ),
    (
        "check_coverage/entries/control_plane.rs",
        include_str!("../../check_coverage/entries/control_plane.rs"),
    ),
    (
        "check_coverage/entries/connectivity.rs",
        include_str!("../../check_coverage/entries/connectivity.rs"),
    ),
    (
        "check_coverage/entries/coverage.rs",
        include_str!("../../check_coverage/entries/coverage.rs"),
    ),
    (
        "check_coverage/entries/memory.rs",
        include_str!("../../check_coverage/entries/memory.rs"),
    ),
    (
        "check_coverage/entries/operator_surface.rs",
        include_str!("../../check_coverage/entries/operator_surface.rs"),
    ),
    (
        "check_coverage/entries/performance.rs",
        include_str!("../../check_coverage/entries/performance.rs"),
    ),
    (
        "check_coverage/entries/performance/file_transfer.rs",
        include_str!("../../check_coverage/entries/performance/file_transfer.rs"),
    ),
    (
        "check_coverage/entries/performance/p2p_remote_artifact.rs",
        include_str!("../../check_coverage/entries/performance/p2p_remote_artifact.rs"),
    ),
    (
        "check_coverage/entries/performance/p2p_remote_media.rs",
        include_str!("../../check_coverage/entries/performance/p2p_remote_media.rs"),
    ),
    (
        "check_coverage/entries/performance/p2p_remote_realtime.rs",
        include_str!("../../check_coverage/entries/performance/p2p_remote_realtime.rs"),
    ),
    (
        "check_coverage/entries/performance/webrtc.rs",
        include_str!("../../check_coverage/entries/performance/webrtc.rs"),
    ),
    (
        "check_coverage/entries/release.rs",
        include_str!("../../check_coverage/entries/release.rs"),
    ),
    (
        "check_coverage/entries/smoke.rs",
        include_str!("../../check_coverage/entries/smoke.rs"),
    ),
    (
        "check_coverage/source.rs",
        include_str!("../../check_coverage/source.rs"),
    ),
];
