pub(super) const SOURCE_FRAGMENTS: &[(&str, &str)] = &[
    ("main.rs", include_str!("../../main.rs")),
    ("main_tests.rs", include_str!("../../main_tests.rs")),
    (
        "main_tests/control_plane.rs",
        include_str!("../../main_tests/control_plane.rs"),
    ),
    (
        "main_tests/parse.rs",
        include_str!("../../main_tests/parse.rs"),
    ),
    (
        "main_tests/parse/check.rs",
        include_str!("../../main_tests/parse/check.rs"),
    ),
    (
        "main_tests/parse/device.rs",
        include_str!("../../main_tests/parse/device.rs"),
    ),
    (
        "main_tests/parse/doctor.rs",
        include_str!("../../main_tests/parse/doctor.rs"),
    ),
    (
        "main_tests/parse/file.rs",
        include_str!("../../main_tests/parse/file.rs"),
    ),
    (
        "main_tests/parse/remote_desktop.rs",
        include_str!("../../main_tests/parse/remote_desktop.rs"),
    ),
    (
        "main_tests/parse/smoke.rs",
        include_str!("../../main_tests/parse/smoke.rs"),
    ),
    (
        "main_tests/parse/test.rs",
        include_str!("../../main_tests/parse/test.rs"),
    ),
    ("auth_commands.rs", include_str!("../../auth_commands.rs")),
    ("auth_support.rs", include_str!("../../auth_support.rs")),
    ("cli_args.rs", include_str!("../../cli_args.rs")),
    ("cli_args/check.rs", include_str!("../../cli_args/check.rs")),
    (
        "cli_args/common.rs",
        include_str!("../../cli_args/common.rs"),
    ),
    (
        "cli_args/doctor.rs",
        include_str!("../../cli_args/doctor.rs"),
    ),
    (
        "cli_args/operator.rs",
        include_str!("../../cli_args/operator.rs"),
    ),
    ("cli_args/smoke.rs", include_str!("../../cli_args/smoke.rs")),
    ("cli_args/test.rs", include_str!("../../cli_args/test.rs")),
    ("cli_dispatch.rs", include_str!("../../cli_dispatch.rs")),
    (
        "cli_dispatch/smoke.rs",
        include_str!("../../cli_dispatch/smoke.rs"),
    ),
    ("cli_metadata.rs", include_str!("../../cli_metadata.rs")),
    (
        "cli_test_support.rs",
        include_str!("../../cli_test_support.rs"),
    ),
    ("cli_text.rs", include_str!("../../cli_text.rs")),
    (
        "connectivity_check.rs",
        include_str!("../../connectivity_check.rs"),
    ),
    (
        "connection_code.rs",
        include_str!("../../connection_code.rs"),
    ),
    (
        "connection_code/connect.rs",
        include_str!("../../connection_code/connect.rs"),
    ),
    (
        "connection_code/create.rs",
        include_str!("../../connection_code/create.rs"),
    ),
    (
        "connection_code/inline_runtime.rs",
        include_str!("../../connection_code/inline_runtime.rs"),
    ),
    (
        "connection_code/inline_state.rs",
        include_str!("../../connection_code/inline_state.rs"),
    ),
    (
        "connection_code/tests.rs",
        include_str!("../../connection_code/tests.rs"),
    ),
    (
        "connection_code_snapshot.rs",
        include_str!("../../connection_code_snapshot.rs"),
    ),
    (
        "connection_code_snapshot/tests.rs",
        include_str!("../../connection_code_snapshot/tests.rs"),
    ),
    (
        "control_plane_doctor.rs",
        include_str!("../../control_plane_doctor.rs"),
    ),
    (
        "control_plane_doctor/checks.rs",
        include_str!("../../control_plane_doctor/checks.rs"),
    ),
    (
        "control_plane_doctor/media_lease.rs",
        include_str!("../../control_plane_doctor/media_lease.rs"),
    ),
    (
        "control_plane_doctor/signaling.rs",
        include_str!("../../control_plane_doctor/signaling.rs"),
    ),
    (
        "device_commands.rs",
        include_str!("../../device_commands.rs"),
    ),
    (
        "device_commands/discover.rs",
        include_str!("../../device_commands/discover.rs"),
    ),
    (
        "device_commands/status.rs",
        include_str!("../../device_commands/status.rs"),
    ),
    (
        "doctor_commands.rs",
        include_str!("../../doctor_commands.rs"),
    ),
    ("doctor_report.rs", include_str!("../../doctor_report.rs")),
    (
        "doctor_report/presentation.rs",
        include_str!("../../doctor_report/presentation.rs"),
    ),
    (
        "doctor_report/tests.rs",
        include_str!("../../doctor_report/tests.rs"),
    ),
    (
        "doctor_report/types.rs",
        include_str!("../../doctor_report/types.rs"),
    ),
    (
        "doctor_report/validation.rs",
        include_str!("../../doctor_report/validation.rs"),
    ),
    ("file_commands.rs", include_str!("../../file_commands.rs")),
    (
        "file_transfer_performance/checks.rs",
        include_str!("../../file_transfer_performance/checks.rs"),
    ),
    (
        "file_transfer_performance/evidence/files.rs",
        include_str!("../../file_transfer_performance/evidence/files.rs"),
    ),
    (
        "file_transfer_performance/evidence/launch.rs",
        include_str!("../../file_transfer_performance/evidence/launch.rs"),
    ),
    (
        "file_transfer_performance/evidence/line.rs",
        include_str!("../../file_transfer_performance/evidence/line.rs"),
    ),
    (
        "file_transfer_performance/evidence.rs",
        include_str!("../../file_transfer_performance/evidence.rs"),
    ),
    (
        "file_transfer_performance.rs",
        include_str!("../../file_transfer_performance.rs"),
    ),
    (
        "internal_commands.rs",
        include_str!("../../internal_commands.rs"),
    ),
    (
        "main_dispatch_tests.rs",
        include_str!("../../main_dispatch_tests.rs"),
    ),
    (
        "main_dispatch_tests/command_wrappers.rs",
        include_str!("../../main_dispatch_tests/command_wrappers.rs"),
    ),
    (
        "main_dispatch_tests/device.rs",
        include_str!("../../main_dispatch_tests/device.rs"),
    ),
    (
        "main_dispatch_tests/file_transfer.rs",
        include_str!("../../main_dispatch_tests/file_transfer.rs"),
    ),
    (
        "main_dispatch_tests/doctor_wrappers.rs",
        include_str!("../../main_dispatch_tests/doctor_wrappers.rs"),
    ),
    (
        "main_dispatch_tests/inline_identity.rs",
        include_str!("../../main_dispatch_tests/inline_identity.rs"),
    ),
    (
        "main_dispatch_tests/operator_entry.rs",
        include_str!("../../main_dispatch_tests/operator_entry.rs"),
    ),
    (
        "main_dispatch_tests/remote_desktop.rs",
        include_str!("../../main_dispatch_tests/remote_desktop.rs"),
    ),
    (
        "main_dispatch_tests/smoke_file_alias.rs",
        include_str!("../../main_dispatch_tests/smoke_file_alias.rs"),
    ),
    ("memory_check.rs", include_str!("../../memory_check.rs")),
    (
        "memory_check/runner.rs",
        include_str!("../../memory_check/runner.rs"),
    ),
    (
        "memory_check/tests.rs",
        include_str!("../../memory_check/tests.rs"),
    ),
    (
        "memory_check/tests/args.rs",
        include_str!("../../memory_check/tests/args.rs"),
    ),
    (
        "memory_check/tests/execution.rs",
        include_str!("../../memory_check/tests/execution.rs"),
    ),
    (
        "operator_status.rs",
        include_str!("../../operator_status.rs"),
    ),
    (
        "operator_status/health.rs",
        include_str!("../../operator_status/health.rs"),
    ),
    (
        "operator_capabilities.rs",
        include_str!("../../operator_capabilities.rs"),
    ),
    (
        "performance_report_target.rs",
        include_str!("../../performance_report_target.rs"),
    ),
    (
        "remote_control_notice_check.rs",
        include_str!("../../remote_control_notice_check.rs"),
    ),
    (
        "remote_desktop_commands.rs",
        include_str!("../../remote_desktop_commands.rs"),
    ),
    ("repo_paths.rs", include_str!("../../repo_paths.rs")),
    (
        "session_commands.rs",
        include_str!("../../session_commands.rs"),
    ),
    (
        "session_commands/presentation.rs",
        include_str!("../../session_commands/presentation.rs"),
    ),
    (
        "session_commands/tests.rs",
        include_str!("../../session_commands/tests.rs"),
    ),
    ("test_commands.rs", include_str!("../../test_commands.rs")),
];
