pub(super) const SOURCE_FRAGMENTS: &[(&str, &str)] = &[
    (
        "p2p_remote_performance_checks.rs",
        include_str!("../../p2p_remote_performance_checks.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime.rs",
        include_str!("../../p2p_remote_performance_checks/realtime.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/common.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/common.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/final_window.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/final_window.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/ios_raw_latency.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/ios_raw_latency.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/mac_tx.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/mac_tx.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/mac_tx/detail.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/mac_tx/detail.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/mac_tx/selected.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/mac_tx/selected.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/mac_tx/verdict.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/mac_tx/verdict.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/metal_render_queue.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/metal_render_queue.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/metal_render_queue/check.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/metal_render_queue/check.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/metal_render_queue/detail.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/metal_render_queue/detail.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/metal_render_queue/selected.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/metal_render_queue/selected.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/metal_render_queue/verdict.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/metal_render_queue/verdict.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/receiver_continuity.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/receiver_continuity.rs"),
    ),
    (
        "p2p_remote_performance_checks/realtime/timing_correlation.rs",
        include_str!("../../p2p_remote_performance_checks/realtime/timing_correlation.rs"),
    ),
    (
        "p2p_remote_performance_checks/video.rs",
        include_str!("../../p2p_remote_performance_checks/video.rs"),
    ),
    (
        "p2p_remote_performance_evidence.rs",
        include_str!("../../p2p_remote_performance_evidence.rs"),
    ),
    (
        "p2p_remote_performance_evidence/audio.rs",
        include_str!("../../p2p_remote_performance_evidence/audio.rs"),
    ),
    (
        "p2p_remote_performance_evidence/files.rs",
        include_str!("../../p2p_remote_performance_evidence/files.rs"),
    ),
    (
        "p2p_remote_performance_evidence/final_window.rs",
        include_str!("../../p2p_remote_performance_evidence/final_window.rs"),
    ),
    (
        "p2p_remote_performance_evidence/final_window/ios.rs",
        include_str!("../../p2p_remote_performance_evidence/final_window/ios.rs"),
    ),
    (
        "p2p_remote_performance_evidence/final_window/mac.rs",
        include_str!("../../p2p_remote_performance_evidence/final_window/mac.rs"),
    ),
    (
        "p2p_remote_performance_evidence/final_window/mac/remote_frame.rs",
        include_str!("../../p2p_remote_performance_evidence/final_window/mac/remote_frame.rs"),
    ),
    (
        "p2p_remote_performance_evidence/final_window/mac/sck_tx.rs",
        include_str!("../../p2p_remote_performance_evidence/final_window/mac/sck_tx.rs"),
    ),
    (
        "p2p_remote_performance_evidence/ios_lan_rx.rs",
        include_str!("../../p2p_remote_performance_evidence/ios_lan_rx.rs"),
    ),
    (
        "p2p_remote_performance_evidence/log_order.rs",
        include_str!("../../p2p_remote_performance_evidence/log_order.rs"),
    ),
    (
        "p2p_remote_performance_evidence/mac_tx.rs",
        include_str!("../../p2p_remote_performance_evidence/mac_tx.rs"),
    ),
    (
        "p2p_remote_performance_evidence/mac_tx/remote_frame.rs",
        include_str!("../../p2p_remote_performance_evidence/mac_tx/remote_frame.rs"),
    ),
    (
        "p2p_remote_performance_evidence/mac_tx/sck_encode_failure.rs",
        include_str!("../../p2p_remote_performance_evidence/mac_tx/sck_encode_failure.rs"),
    ),
    (
        "p2p_remote_performance_evidence/mac_tx/sck_encoder.rs",
        include_str!("../../p2p_remote_performance_evidence/mac_tx/sck_encoder.rs"),
    ),
    (
        "p2p_remote_performance_evidence/mac_tx/sck_tx.rs",
        include_str!("../../p2p_remote_performance_evidence/mac_tx/sck_tx.rs"),
    ),
    (
        "p2p_remote_performance_evidence/markers.rs",
        include_str!("../../p2p_remote_performance_evidence/markers.rs"),
    ),
    (
        "p2p_remote_performance_evidence/metal_render.rs",
        include_str!("../../p2p_remote_performance_evidence/metal_render.rs"),
    ),
    (
        "p2p_remote_performance_evidence/pass_window.rs",
        include_str!("../../p2p_remote_performance_evidence/pass_window.rs"),
    ),
    (
        "p2p_remote_performance_evidence/remote_desktop_status.rs",
        include_str!("../../p2p_remote_performance_evidence/remote_desktop_status.rs"),
    ),
    (
        "p2p_remote_performance_evidence/route.rs",
        include_str!("../../p2p_remote_performance_evidence/route.rs"),
    ),
    (
        "p2p_remote_performance_evidence/types.rs",
        include_str!("../../p2p_remote_performance_evidence/types.rs"),
    ),
    (
        "p2p_remote_performance.rs",
        include_str!("../../p2p_remote_performance.rs"),
    ),
    (
        "performance_budgets.rs",
        include_str!("../../performance_budgets.rs"),
    ),
    (
        "performance_commands.rs",
        include_str!("../../performance_commands.rs"),
    ),
    (
        "performance_evidence.rs",
        include_str!("../../performance_evidence.rs"),
    ),
    (
        "performance_evidence/signed_kem_refresh.rs",
        include_str!("../../performance_evidence/signed_kem_refresh.rs"),
    ),
    (
        "performance_evidence/signed_kem_refresh/line_update.rs",
        include_str!("../../performance_evidence/signed_kem_refresh/line_update.rs"),
    ),
    (
        "performance_evidence/signed_kem_refresh/protocol_identity_binding.rs",
        include_str!("../../performance_evidence/signed_kem_refresh/protocol_identity_binding.rs"),
    ),
    (
        "performance_evidence/text.rs",
        include_str!("../../performance_evidence/text.rs"),
    ),
    (
        "performance_check_names.rs",
        include_str!("../../performance_check_names.rs"),
    ),
];
