pub(super) const SOURCE_FRAGMENTS: &[(&str, &str)] = &[
    (
        "performance_tests.rs",
        include_str!("../../performance_tests.rs"),
    ),
    (
        "performance_tests/file_transfer.rs",
        include_str!("../../performance_tests/file_transfer.rs"),
    ),
    (
        "performance_tests/file_transfer/artifact_failures.rs",
        include_str!("../../performance_tests/file_transfer/artifact_failures.rs"),
    ),
    (
        "performance_tests/file_transfer/artifact_failures/bidirectional.rs",
        include_str!("../../performance_tests/file_transfer/artifact_failures/bidirectional.rs"),
    ),
    (
        "performance_tests/file_transfer/artifact_failures/failed_stage.rs",
        include_str!("../../performance_tests/file_transfer/artifact_failures/failed_stage.rs"),
    ),
    (
        "performance_tests/file_transfer/artifact_failures/ios_launch.rs",
        include_str!("../../performance_tests/file_transfer/artifact_failures/ios_launch.rs"),
    ),
    (
        "performance_tests/file_transfer/artifact_failures/xwing_unknown_suite.rs",
        include_str!(
            "../../performance_tests/file_transfer/artifact_failures/xwing_unknown_suite.rs"
        ),
    ),
    (
        "performance_tests/file_transfer/fixture_gates.rs",
        include_str!("../../performance_tests/file_transfer/fixture_gates.rs"),
    ),
    (
        "performance_tests/file_transfer/signed_kem_refresh.rs",
        include_str!("../../performance_tests/file_transfer/signed_kem_refresh.rs"),
    ),
    (
        "performance_tests/p2p_remote.rs",
        include_str!("../../performance_tests/p2p_remote.rs"),
    ),
    (
        "performance_tests/p2p_remote/artifact_integrity.rs",
        include_str!("../../performance_tests/p2p_remote/artifact_integrity.rs"),
    ),
    (
        "performance_tests/p2p_remote/artifact_integrity/failed_stage.rs",
        include_str!("../../performance_tests/p2p_remote/artifact_integrity/failed_stage.rs"),
    ),
    (
        "performance_tests/p2p_remote/artifact_integrity/smoke_final.rs",
        include_str!("../../performance_tests/p2p_remote/artifact_integrity/smoke_final.rs"),
    ),
    (
        "performance_tests/p2p_remote/artifact_integrity/unknown_suite.rs",
        include_str!("../../performance_tests/p2p_remote/artifact_integrity/unknown_suite.rs"),
    ),
    (
        "performance_tests/p2p_remote/artifact_sources.rs",
        include_str!("../../performance_tests/p2p_remote/artifact_sources.rs"),
    ),
    (
        "performance_tests/p2p_remote/baseline.rs",
        include_str!("../../performance_tests/p2p_remote/baseline.rs"),
    ),
    (
        "performance_tests/p2p_remote/final_window.rs",
        include_str!("../../performance_tests/p2p_remote/final_window.rs"),
    ),
    (
        "performance_tests/p2p_remote/final_window/duration.rs",
        include_str!("../../performance_tests/p2p_remote/final_window/duration.rs"),
    ),
    (
        "performance_tests/p2p_remote/final_window/local_console_timestamps.rs",
        include_str!("../../performance_tests/p2p_remote/final_window/local_console_timestamps.rs"),
    ),
    (
        "performance_tests/p2p_remote/final_window/missing_samples.rs",
        include_str!("../../performance_tests/p2p_remote/final_window/missing_samples.rs"),
    ),
    (
        "performance_tests/p2p_remote/hevc_main_path.rs",
        include_str!("../../performance_tests/p2p_remote/hevc_main_path.rs"),
    ),
    (
        "performance_tests/p2p_remote/lan_route.rs",
        include_str!("../../performance_tests/p2p_remote/lan_route.rs"),
    ),
    (
        "performance_tests/p2p_remote/mac_tx.rs",
        include_str!("../../performance_tests/p2p_remote/mac_tx.rs"),
    ),
    (
        "performance_tests/p2p_remote/mac_tx/final_window_sent_fps.rs",
        include_str!("../../performance_tests/p2p_remote/mac_tx/final_window_sent_fps.rs"),
    ),
    (
        "performance_tests/p2p_remote/mac_tx/sender_gate.rs",
        include_str!("../../performance_tests/p2p_remote/mac_tx/sender_gate.rs"),
    ),
    (
        "performance_tests/realtime.rs",
        include_str!("../../performance_tests/realtime.rs"),
    ),
    (
        "performance_tests/realtime/audio.rs",
        include_str!("../../performance_tests/realtime/audio.rs"),
    ),
    (
        "performance_tests/realtime/ios_window.rs",
        include_str!("../../performance_tests/realtime/ios_window.rs"),
    ),
    (
        "performance_tests/realtime/metal_render.rs",
        include_str!("../../performance_tests/realtime/metal_render.rs"),
    ),
    (
        "performance_tests/realtime/raw_latency.rs",
        include_str!("../../performance_tests/realtime/raw_latency.rs"),
    ),
    (
        "performance_tests/realtime/timing_correlation.rs",
        include_str!("../../performance_tests/realtime/timing_correlation.rs"),
    ),
    (
        "performance_tests/signed_kem.rs",
        include_str!("../../performance_tests/signed_kem.rs"),
    ),
    (
        "performance_tests/signed_kem/fallback_parser.rs",
        include_str!("../../performance_tests/signed_kem/fallback_parser.rs"),
    ),
    (
        "performance_tests/signed_kem/golden_fixtures.rs",
        include_str!("../../performance_tests/signed_kem/golden_fixtures.rs"),
    ),
    (
        "performance_tests/signed_kem/parser_source_events.rs",
        include_str!("../../performance_tests/signed_kem/parser_source_events.rs"),
    ),
    (
        "performance_tests/signed_kem/protocol_identity.rs",
        include_str!("../../performance_tests/signed_kem/protocol_identity.rs"),
    ),
    (
        "performance_tests/signed_kem/refresh_budgets.rs",
        include_str!("../../performance_tests/signed_kem/refresh_budgets.rs"),
    ),
    (
        "performance_tests/signed_kem/refresh_lifecycle.rs",
        include_str!("../../performance_tests/signed_kem/refresh_lifecycle.rs"),
    ),
    (
        "performance_tests/signed_kem/timestamp_ordering.rs",
        include_str!("../../performance_tests/signed_kem/timestamp_ordering.rs"),
    ),
    (
        "performance_tests/signed_kem/xwing_order.rs",
        include_str!("../../performance_tests/signed_kem/xwing_order.rs"),
    ),
];
