pub(super) const SOURCE_FRAGMENTS: &[(&str, &str)] = &[
    (
        "Scripts/check_macos_release_readiness.sh",
        include_str!("../../../../../../Scripts/check_macos_release_readiness.sh"),
    ),
    (
        "Scripts/generate_macos_update_manifest.swift",
        include_str!("../../../../../../Scripts/generate_macos_update_manifest.swift"),
    ),
    (
        "Scripts/publish_macos_update_release.sh",
        include_str!("../../../../../../Scripts/publish_macos_update_release.sh"),
    ),
    (
        "Scripts/validate_macos_update_manifest.sh",
        include_str!("../../../../../../Scripts/validate_macos_update_manifest.sh"),
    ),
    (
        "Scripts/validate_macos_release_artifact_run.sh",
        include_str!("../../../../../../Scripts/validate_macos_release_artifact_run.sh"),
    ),
    (
        "Scripts/validate_macos_release_public_artifacts.sh",
        include_str!("../../../../../../Scripts/validate_macos_release_public_artifacts.sh"),
    ),
    (
        ".github/workflows/macos-release-readiness.yml",
        include_str!("../../../../../../.github/workflows/macos-release-readiness.yml"),
    ),
    (
        "Scripts/verify_xcode_toolchain.sh",
        include_str!("../../../../../../Scripts/verify_xcode_toolchain.sh"),
    ),
    (
        "Sources/SkyBridgeCompassApp/Services/AppUpdateChecker.swift",
        include_str!(
            "../../../../../../Sources/SkyBridgeCompassApp/Services/AppUpdateChecker.swift"
        ),
    ),
    (
        "Sources/SkyBridgeCore/Updates/AppUpdateManifest.swift",
        include_str!("../../../../../../Sources/SkyBridgeCore/Updates/AppUpdateManifest.swift"),
    ),
    (
        "Sources/SkyBridgeCompassApp/Info.plist",
        include_str!("../../../../../../Sources/SkyBridgeCompassApp/Info.plist"),
    ),
    (
        "Sources/SkyBridgeCompassApp/ViewModels/CloudDeviceListViewModel.swift",
        include_str!(
            "../../../../../../Sources/SkyBridgeCompassApp/ViewModels/CloudDeviceListViewModel.swift"
        ),
    ),
    (
        "Sources/SkyBridgeCompassApp/ViewModels/CloudDevicePresentationPolicy.swift",
        include_str!(
            "../../../../../../Sources/SkyBridgeCompassApp/ViewModels/CloudDevicePresentationPolicy.swift"
        ),
    ),
    (
        "Package.swift",
        include_str!("../../../../../../Package.swift"),
    ),
    (
        "SkyBridge Compass iOS/Package.swift",
        include_str!("../../../../../../SkyBridge Compass iOS/Package.swift"),
    ),
    (
        "Sources/SkyBridgeCore/RemoteControl/RemoteControlSecurityNotice.swift",
        include_str!(
            "../../../../../../Sources/SkyBridgeCore/RemoteControl/RemoteControlSecurityNotice.swift"
        ),
    ),
    (
        "Tests/SkyBridgeCoreTests/RemoteControlSecurityNoticeTests.swift",
        include_str!(
            "../../../../../../Tests/SkyBridgeCoreTests/RemoteControlSecurityNoticeTests.swift"
        ),
    ),
    (
        "Tests/SkyBridgeCoreTests/UnifiedOnlineDeviceManagerDedupeTests.swift",
        include_str!(
            "../../../../../../Tests/SkyBridgeCoreTests/UnifiedOnlineDeviceManagerDedupeTests.swift"
        ),
    ),
    (
        "Tests/SkyBridgeCoreTests/MacTrustedDeviceTrustActionsTests.swift",
        include_str!(
            "../../../../../../Tests/SkyBridgeCoreTests/MacTrustedDeviceTrustActionsTests.swift"
        ),
    ),
];
