pub(super) const SOURCE_FRAGMENTS: &[(&str, &str)] = &[
    ("smoke_suite.rs", include_str!("../../smoke_suite.rs")),
    (
        "smoke_suite/plan.rs",
        include_str!("../../smoke_suite/plan.rs"),
    ),
    (
        "smoke_suite/plan/benchmarks.rs",
        include_str!("../../smoke_suite/plan/benchmarks.rs"),
    ),
    (
        "smoke_suite/plan/real_device.rs",
        include_str!("../../smoke_suite/plan/real_device.rs"),
    ),
    (
        "smoke_suite/plan/standard.rs",
        include_str!("../../smoke_suite/plan/standard.rs"),
    ),
    (
        "smoke_suite/runner.rs",
        include_str!("../../smoke_suite/runner.rs"),
    ),
    (
        "smoke_suite/tests.rs",
        include_str!("../../smoke_suite/tests.rs"),
    ),
    (
        "smoke_suite/tests/dry_run.rs",
        include_str!("../../smoke_suite/tests/dry_run.rs"),
    ),
    (
        "smoke_suite/tests/option_mapping.rs",
        include_str!("../../smoke_suite/tests/option_mapping.rs"),
    ),
    (
        "smoke_suite/tests/plan_runner.rs",
        include_str!("../../smoke_suite/tests/plan_runner.rs"),
    ),
    (
        "smoke_suite/tests/real_device_profiles.rs",
        include_str!("../../smoke_suite/tests/real_device_profiles.rs"),
    ),
    (
        "smoke_suite/tests/real_device_profiles/aggregate_profile.rs",
        include_str!("../../smoke_suite/tests/real_device_profiles/aggregate_profile.rs"),
    ),
    (
        "smoke_suite/tests/real_device_profiles/file_transfer_profile.rs",
        include_str!("../../smoke_suite/tests/real_device_profiles/file_transfer_profile.rs"),
    ),
    (
        "smoke_suite/tests/real_device_profiles/resolution_matrix.rs",
        include_str!("../../smoke_suite/tests/real_device_profiles/resolution_matrix.rs"),
    ),
    (
        "smoke_suite/tests/validation.rs",
        include_str!("../../smoke_suite/tests/validation.rs"),
    ),
];
