pub(super) const SOURCE_FRAGMENTS: &[(&str, &str)] = &[
    (
        "webrtc_media_doctor_tests.rs",
        include_str!("../../webrtc_media_doctor_tests.rs"),
    ),
    (
        "webrtc_media_doctor_tests/audio_counters.rs",
        include_str!("../../webrtc_media_doctor_tests/audio_counters.rs"),
    ),
    (
        "webrtc_media_doctor_tests/audio_playback.rs",
        include_str!("../../webrtc_media_doctor_tests/audio_playback.rs"),
    ),
    (
        "webrtc_media_doctor_tests/audio_playback/continuity_failures.rs",
        include_str!("../../webrtc_media_doctor_tests/audio_playback/continuity_failures.rs"),
    ),
    (
        "webrtc_media_doctor_tests/audio_playback/continuity_failures/jitter_eviction.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/audio_playback/continuity_failures/jitter_eviction.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/audio_playback/continuity_failures/underflow.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/audio_playback/continuity_failures/underflow.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/audio_playback/playout_pressure.rs",
        include_str!("../../webrtc_media_doctor_tests/audio_playback/playout_pressure.rs"),
    ),
    (
        "webrtc_media_doctor_tests/audio_playback/rx_startup.rs",
        include_str!("../../webrtc_media_doctor_tests/audio_playback/rx_startup.rs"),
    ),
    (
        "webrtc_media_doctor_tests/audio_playback/schedule_resilience.rs",
        include_str!("../../webrtc_media_doctor_tests/audio_playback/schedule_resilience.rs"),
    ),
    (
        "webrtc_media_doctor_tests/audio_playback/schedule_resilience/absorbed_arrival_spike.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/audio_playback/schedule_resilience/absorbed_arrival_spike.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/audio_playback/schedule_resilience/rendered_frames_window_reset.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/audio_playback/schedule_resilience/rendered_frames_window_reset.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/audio_playback/schedule_resilience/target_queue_shortfall.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/audio_playback/schedule_resilience/target_queue_shortfall.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/audio_playback/soft_bridged_underflow.rs",
        include_str!("../../webrtc_media_doctor_tests/audio_playback/soft_bridged_underflow.rs"),
    ),
    (
        "webrtc_media_doctor_tests/audio_playback/soft_bridged_underflow/bounded.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/audio_playback/soft_bridged_underflow/bounded.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/audio_playback/soft_bridged_underflow/excessive.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/audio_playback/soft_bridged_underflow/excessive.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/capture_encode.rs",
        include_str!("../../webrtc_media_doctor_tests/capture_encode.rs"),
    ),
    (
        "webrtc_media_doctor_tests/capture_encode/sck.rs",
        include_str!("../../webrtc_media_doctor_tests/capture_encode/sck.rs"),
    ),
    (
        "webrtc_media_doctor_tests/capture_encode/vt.rs",
        include_str!("../../webrtc_media_doctor_tests/capture_encode/vt.rs"),
    ),
    (
        "webrtc_media_doctor_tests/diagnostics_baseline.rs",
        include_str!("../../webrtc_media_doctor_tests/diagnostics_baseline.rs"),
    ),
    (
        "webrtc_media_doctor_tests/diagnostics_baseline/audio_endpoint.rs",
        include_str!("../../webrtc_media_doctor_tests/diagnostics_baseline/audio_endpoint.rs"),
    ),
    (
        "webrtc_media_doctor_tests/diagnostics_baseline/ordering.rs",
        include_str!("../../webrtc_media_doctor_tests/diagnostics_baseline/ordering.rs"),
    ),
    (
        "webrtc_media_doctor_tests/diagnostics_baseline/plain_log.rs",
        include_str!("../../webrtc_media_doctor_tests/diagnostics_baseline/plain_log.rs"),
    ),
    (
        "webrtc_media_doctor_tests/diagnostics_baseline/structured_jsonl.rs",
        include_str!("../../webrtc_media_doctor_tests/diagnostics_baseline/structured_jsonl.rs"),
    ),
    (
        "webrtc_media_doctor_tests/fallback_strict.rs",
        include_str!("../../webrtc_media_doctor_tests/fallback_strict.rs"),
    ),
    (
        "webrtc_media_doctor_tests/relay_bind.rs",
        include_str!("../../webrtc_media_doctor_tests/relay_bind.rs"),
    ),
    (
        "webrtc_media_doctor_tests/relay_bind/failures.rs",
        include_str!("../../webrtc_media_doctor_tests/relay_bind/failures.rs"),
    ),
    (
        "webrtc_media_doctor_tests/relay_bind/optimistic.rs",
        include_str!("../../webrtc_media_doctor_tests/relay_bind/optimistic.rs"),
    ),
    (
        "webrtc_media_doctor_tests/resolution_sources.rs",
        include_str!("../../webrtc_media_doctor_tests/resolution_sources.rs"),
    ),
    (
        "webrtc_media_doctor_tests/resolution_sources/native_receiver_sources.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/resolution_sources/native_receiver_sources.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/resolution_sources/receiver_resolution_rules.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/resolution_sources/receiver_resolution_rules.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/resolution_sources/visible_receiver_dimensions.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/resolution_sources/visible_receiver_dimensions.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/resolution_sources/visible_receiver_dimensions/exact_resolution.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/resolution_sources/visible_receiver_dimensions/exact_resolution.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/resolution_sources/visible_receiver_dimensions/status_logs.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/resolution_sources/visible_receiver_dimensions/status_logs.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/startup_artifact_resolution.rs",
        include_str!("../../webrtc_media_doctor_tests/startup_artifact_resolution.rs"),
    ),
    (
        "webrtc_media_doctor_tests/startup_artifact_resolution/explicit_artifact.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/startup_artifact_resolution/explicit_artifact.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/startup_artifact_resolution/latest.rs",
        include_str!("../../webrtc_media_doctor_tests/startup_artifact_resolution/latest.rs"),
    ),
    (
        "webrtc_media_doctor_tests/startup_artifact_resolution/startup_resilience.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/startup_artifact_resolution/startup_resilience.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/video_render.rs",
        include_str!("../../webrtc_media_doctor_tests/video_render.rs"),
    ),
    (
        "webrtc_media_doctor_tests/video_render/high_fps_rtc_stats.rs",
        include_str!("../../webrtc_media_doctor_tests/video_render/high_fps_rtc_stats.rs"),
    ),
    (
        "webrtc_media_doctor_tests/video_render/high_fps_rtc_stats/rtc_stats_failures.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/video_render/high_fps_rtc_stats/rtc_stats_failures.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/video_render/high_fps_rtc_stats/success.rs",
        include_str!("../../webrtc_media_doctor_tests/video_render/high_fps_rtc_stats/success.rs"),
    ),
    (
        "webrtc_media_doctor_tests/video_render/high_fps_rtc_stats/visible_render_requirement.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/video_render/high_fps_rtc_stats/visible_render_requirement.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/video_render/video_only.rs",
        include_str!("../../webrtc_media_doctor_tests/video_render/video_only.rs"),
    ),
    (
        "webrtc_media_doctor_tests/video_render/visible_render_gate.rs",
        include_str!("../../webrtc_media_doctor_tests/video_render/visible_render_gate.rs"),
    ),
    (
        "webrtc_media_doctor_tests/video_render/visible_render_gate/fallback.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/video_render/visible_render_gate/fallback.rs"
        ),
    ),
    (
        "webrtc_media_doctor_tests/video_render/visible_render_gate/low_fps.rs",
        include_str!("../../webrtc_media_doctor_tests/video_render/visible_render_gate/low_fps.rs"),
    ),
    (
        "webrtc_media_doctor_tests/video_render/visible_render_gate/smoke_overlay.rs",
        include_str!(
            "../../webrtc_media_doctor_tests/video_render/visible_render_gate/smoke_overlay.rs"
        ),
    ),
];
