pub(super) const SOURCE_FRAGMENTS: &[(&str, &str)] = &[
    (
        "webrtc_media_doctor.rs",
        include_str!("../../webrtc_media_doctor.rs"),
    ),
    (
        "webrtc_media_doctor/checks.rs",
        include_str!("../../webrtc_media_doctor/checks.rs"),
    ),
    (
        "webrtc_media_doctor/checks/audio.rs",
        include_str!("../../webrtc_media_doctor/checks/audio.rs"),
    ),
    (
        "webrtc_media_doctor/checks/audio/playback.rs",
        include_str!("../../webrtc_media_doctor/checks/audio/playback.rs"),
    ),
    (
        "webrtc_media_doctor/checks/audio/relay.rs",
        include_str!("../../webrtc_media_doctor/checks/audio/relay.rs"),
    ),
    (
        "webrtc_media_doctor/checks/continuity.rs",
        include_str!("../../webrtc_media_doctor/checks/continuity.rs"),
    ),
    (
        "webrtc_media_doctor/checks/diagnostics.rs",
        include_str!("../../webrtc_media_doctor/checks/diagnostics.rs"),
    ),
    (
        "webrtc_media_doctor/checks/fault_stage.rs",
        include_str!("../../webrtc_media_doctor/checks/fault_stage.rs"),
    ),
    (
        "webrtc_media_doctor/checks/video.rs",
        include_str!("../../webrtc_media_doctor/checks/video.rs"),
    ),
    (
        "webrtc_media_doctor/checks/video/fps.rs",
        include_str!("../../webrtc_media_doctor/checks/video/fps.rs"),
    ),
    (
        "webrtc_media_doctor/checks/video/render.rs",
        include_str!("../../webrtc_media_doctor/checks/video/render.rs"),
    ),
    (
        "webrtc_media_doctor/checks/video/resolution.rs",
        include_str!("../../webrtc_media_doctor/checks/video/resolution.rs"),
    ),
    (
        "webrtc_media_doctor/checks/video/sck.rs",
        include_str!("../../webrtc_media_doctor/checks/video/sck.rs"),
    ),
    (
        "webrtc_media_doctor/evidence.rs",
        include_str!("../../webrtc_media_doctor/evidence.rs"),
    ),
    (
        "webrtc_media_doctor/evidence/audio.rs",
        include_str!("../../webrtc_media_doctor/evidence/audio.rs"),
    ),
    (
        "webrtc_media_doctor/evidence/observation.rs",
        include_str!("../../webrtc_media_doctor/evidence/observation.rs"),
    ),
    (
        "webrtc_media_doctor/evidence/observation/audio_playout_pressure.rs",
        include_str!("../../webrtc_media_doctor/evidence/observation/audio_playout_pressure.rs"),
    ),
    (
        "webrtc_media_doctor/evidence/observation/freshness.rs",
        include_str!("../../webrtc_media_doctor/evidence/observation/freshness.rs"),
    ),
    (
        "webrtc_media_doctor/evidence/observation/metrics.rs",
        include_str!("../../webrtc_media_doctor/evidence/observation/metrics.rs"),
    ),
    (
        "webrtc_media_doctor/evidence/render.rs",
        include_str!("../../webrtc_media_doctor/evidence/render.rs"),
    ),
    (
        "webrtc_media_doctor/evidence/types.rs",
        include_str!("../../webrtc_media_doctor/evidence/types.rs"),
    ),
    (
        "webrtc_media_doctor/evidence/video.rs",
        include_str!("../../webrtc_media_doctor/evidence/video.rs"),
    ),
    (
        "webrtc_media_doctor/evidence/video/native.rs",
        include_str!("../../webrtc_media_doctor/evidence/video/native.rs"),
    ),
    (
        "webrtc_media_doctor/evidence/video/sck.rs",
        include_str!("../../webrtc_media_doctor/evidence/video/sck.rs"),
    ),
    (
        "webrtc_media_doctor/line_extract.rs",
        include_str!("../../webrtc_media_doctor/line_extract.rs"),
    ),
    (
        "webrtc_media_doctor/line_extract/audio.rs",
        include_str!("../../webrtc_media_doctor/line_extract/audio.rs"),
    ),
    (
        "webrtc_media_doctor/line_extract/fallback.rs",
        include_str!("../../webrtc_media_doctor/line_extract/fallback.rs"),
    ),
    (
        "webrtc_media_doctor/line_extract/video.rs",
        include_str!("../../webrtc_media_doctor/line_extract/video.rs"),
    ),
];
