pub(super) const SOURCE_FRAGMENTS: &[(&str, &str)] = &[
    (
        "webrtc_media_artifacts.rs",
        include_str!("../../webrtc_media_artifacts.rs"),
    ),
    (
        "webrtc_media_artifacts/latest.rs",
        include_str!("../../webrtc_media_artifacts/latest.rs"),
    ),
    (
        "webrtc_media_artifacts/sources.rs",
        include_str!("../../webrtc_media_artifacts/sources.rs"),
    ),
    (
        "webrtc_media_dimensions.rs",
        include_str!("../../webrtc_media_dimensions.rs"),
    ),
    (
        "webrtc_media_parse.rs",
        include_str!("../../webrtc_media_parse.rs"),
    ),
    (
        "webrtc_media_parse/timestamp.rs",
        include_str!("../../webrtc_media_parse/timestamp.rs"),
    ),
    (
        "webrtc_media_parse/value.rs",
        include_str!("../../webrtc_media_parse/value.rs"),
    ),
    (
        "webrtc_media_summary.rs",
        include_str!("../../webrtc_media_summary.rs"),
    ),
    (
        "webrtc_smoke_gate.rs",
        include_str!("../../webrtc_smoke_gate.rs"),
    ),
    (
        "webrtc_smoke_gate/policy.rs",
        include_str!("../../webrtc_smoke_gate/policy.rs"),
    ),
];
