name: SkyBridgeCompass-iOS

options:
  bundleIdPrefix: com.skybridge
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"

packages:
  WebRTCLocal:
    path: LocalPackages/WebRTCLocal

targets:
  SkyBridgeCompass-iOS:
    type: application
    platform: iOS
    info:
      path: "SkyBridgeCompassiOS/Supporting Files/Info.plist"
    sources:
      - path: SkyBridgeCompassiOS/Sources
      - path: "SkyBridgeCompassiOS/Supporting Files/LaunchScreen.storyboard"
        buildPhase: resources
      - path: SkyBridgeCompassiOS/Resources
        buildPhase: resources
    dependencies:
      - sdk: AppIntents.framework
      - package: WebRTCLocal
        product: WebRTC
      - target: SkyBridgeCompass-Widgets
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.skybridge.compass.ios
        DEVELOPMENT_TEAM: YKUPL7Z869
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: "SkyBridgeCompassiOS/Supporting Files/Info.plist"
        SWIFT_STRICT_CONCURRENCY: targeted
        OTHER_SWIFT_FLAGS:
          - "$(inherited)"
          - "-Xcc"
          - "-I"
          - "-Xcc"
          - "$(SRCROOT)/../Sources/Vendor/WebRTCHeaders"
          - "-Xcc"
          - "-Wno-incomplete-umbrella"
        OTHER_CFLAGS: "$(inherited) -Wno-incomplete-umbrella"
        OTHER_CPLUSPLUSFLAGS: "$(inherited) -Wno-incomplete-umbrella"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited)"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS[sdk=iphoneos26*]: "$(inherited) HAS_APPLE_PQC_SDK"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS[sdk=iphonesimulator26*]: "$(inherited) HAS_APPLE_PQC_SDK"
        # WebRTC (third-party binary package) exposes an incomplete umbrella header on iOS.
        # Keep this warning enabled for our own frameworks; suppress only at app integration boundary.
        CLANG_WARN_INCOMPLETE_UMBRELLA: NO
        # Auto-enable Apple PQC compile gate only when building against iOS 26 SDK.
        # This keeps older SDK builds portable while allowing 26.x builds to use native PQC.

  SkyBridgeCompass-Widgets:
    type: app-extension
    platform: iOS
    info:
      path: "Widgets/Info.plist"
    sources:
      - path: Widgets
      - path: SkyBridgeCompassiOS/Sources/LiveActivities/SkyBridgeActivityAttributes.swift
    dependencies:
      - sdk: WidgetKit.framework
      - sdk: ActivityKit.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.skybridge.compass.ios.widgets
        DEVELOPMENT_TEAM: YKUPL7Z869
        INFOPLIST_FILE: "Widgets/Info.plist"
        SWIFT_STRICT_CONCURRENCY: targeted
        # Widgets do not need HAS_APPLE_PQC_SDK; keep build conditions minimal for portability.

schemes:
  SkyBridgeCompass-iOS:
    build:
      targets:
        SkyBridgeCompass-iOS: all
        SkyBridgeCompass-Widgets: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
