use std::path::PathBuf;

use time::OffsetDateTime;

use crate::webrtc_media_dimensions::VideoDimensions;

#[derive(Debug, Clone)]
pub(in crate::webrtc_media_doctor) struct ObservedMetric<T> {
    pub(in crate::webrtc_media_doctor) value: T,
    pub(in crate::webrtc_media_doctor) sequence: usize,
    pub(in crate::webrtc_media_doctor) evidence: String,
}

#[derive(Debug, Default)]
pub(in crate::webrtc_media_doctor) struct CounterObservation {
    pub(in crate::webrtc_media_doctor) latest: Option<ObservedMetric<u64>>,
    pub(in crate::webrtc_media_doctor) lowest: Option<ObservedMetric<u64>>,
    pub(in crate::webrtc_media_doctor) first_positive: Option<ObservedMetric<u64>>,
    pub(in crate::webrtc_media_doctor) latest_positive: Option<ObservedMetric<u64>>,
    pub(in crate::webrtc_media_doctor) zero_after_positive: Option<ObservedMetric<u64>>,
    pub(in crate::webrtc_media_doctor) decrease_after_positive: Option<ObservedMetric<u64>>,
    pub(in crate::webrtc_media_doctor) positive_count: usize,
    pub(in crate::webrtc_media_doctor) seen_positive: bool,
}

#[derive(Debug, Default)]
pub(in crate::webrtc_media_doctor) struct WebRtcMediaEvidence {
    pub(in crate::webrtc_media_doctor) attempted_sources: Vec<PathBuf>,
    pub(in crate::webrtc_media_doctor) read_sources: Vec<PathBuf>,
    pub(in crate::webrtc_media_doctor) read_errors: Vec<String>,
    pub(in crate::webrtc_media_doctor) matched_lines: usize,
    pub(in crate::webrtc_media_doctor) latest_at: Option<OffsetDateTime>,
    pub(in crate::webrtc_media_doctor) latest_video_evidence_at: Option<OffsetDateTime>,
    pub(in crate::webrtc_media_doctor) latest_receiver_evidence_at: Option<OffsetDateTime>,
    pub(in crate::webrtc_media_doctor) latest_audio_tx_evidence_at: Option<OffsetDateTime>,
    pub(in crate::webrtc_media_doctor) latest_audio_rx_evidence_at: Option<OffsetDateTime>,
    pub(in crate::webrtc_media_doctor) lowest_fps: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) latest_fps: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) audio_tx_captured: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_tx_encoded: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_tx_sent: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_tx_captured_total: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_tx_encoded_total: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_tx_sent_total: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_drops: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_drops_total: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_rx_recv: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_rx_decoded: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_rx_played: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_rx_recv_total: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_rx_decoded_total: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_rx_played_total: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_rendered_frames: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_underflow: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_bridged_underflow: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_rebuffer: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_playback_drop: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_jitter_evicted: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_jitter_late: CounterObservation,
    pub(in crate::webrtc_media_doctor) audio_lowest_schedule_lead_ms: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) audio_highest_arrival_p95_ms: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) audio_highest_arrival_max_ms: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) audio_playout_pressure: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) audio_tx_missing_viewer_endpoint:
        Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) audio_tx_relay_failure: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) audio_tx_relay_bind_pending: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) audio_rx_relay_bind_failure: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) native_video_state: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) native_video_failure: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) native_video_submitted: CounterObservation,
    pub(in crate::webrtc_media_doctor) native_video_frames_encoded: CounterObservation,
    pub(in crate::webrtc_media_doctor) native_video_frames_sent: CounterObservation,
    pub(in crate::webrtc_media_doctor) native_video_key_frames_encoded: CounterObservation,
    pub(in crate::webrtc_media_doctor) native_video_packets_sent: CounterObservation,
    pub(in crate::webrtc_media_doctor) native_video_bytes_sent: CounterObservation,
    pub(in crate::webrtc_media_doctor) native_video_codec: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) native_video_encoder: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) native_video_quality_limit: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) native_video_encode_fps: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) native_video_lowest_encode_fps: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) native_video_target_bitrate: CounterObservation,
    pub(in crate::webrtc_media_doctor) native_video_available_outgoing_bitrate: CounterObservation,
    pub(in crate::webrtc_media_doctor) native_video_current_rtt: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) native_video_remote_rtt: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) native_video_remote_packets_lost:
        Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) native_video_remote_jitter: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) sck_captured: CounterObservation,
    pub(in crate::webrtc_media_doctor) sck_meaningful: CounterObservation,
    pub(in crate::webrtc_media_doctor) sck_encoded: CounterObservation,
    pub(in crate::webrtc_media_doctor) sck_encoded_bytes: CounterObservation,
    pub(in crate::webrtc_media_doctor) sck_capture_fps: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) sck_meaningful_fps: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) sck_encoded_fps: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) sck_encode_latency_p50_ms: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) sck_encode_latency_p95_ms: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) sck_encode_latency_max_ms: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) sck_encode_failures: CounterObservation,
    pub(in crate::webrtc_media_doctor) sck_codec: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) native_video_receiver_frame: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) native_video_receiver_dimensions:
        Option<ObservedMetric<VideoDimensions>>,
    pub(in crate::webrtc_media_doctor) native_video_receiver_dimensions_are_visible: bool,
    pub(in crate::webrtc_media_doctor) native_video_render_frame: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) native_video_render_source: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) native_video_render_surface: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) native_video_render_dimensions:
        Option<ObservedMetric<VideoDimensions>>,
    pub(in crate::webrtc_media_doctor) native_video_render_dimensions_are_visible: bool,
    pub(in crate::webrtc_media_doctor) native_video_render_fps: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) native_video_lowest_render_fps: Option<ObservedMetric<f64>>,
    pub(in crate::webrtc_media_doctor) strict_media_failure: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) fallback_producer_failure: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) stale_fallback: Option<ObservedMetric<String>>,
    pub(in crate::webrtc_media_doctor) backpressure: Option<ObservedMetric<String>>,
}
