// Generated by Scripts/generate_visual_parity_assets.py. Do not edit by hand.
import CoreGraphics
import SwiftUI

public enum VisualParityTokenSet {
    public enum Layout {
        public static let captureSize = CGSize(width: 1200, height: 800)
        public static let windowSize = CGSize(width: 1200, height: 800)
        public static let shellOuterMargin: CGFloat = 26
        public static let shellSurfacePadding: CGFloat = 12
        public static let shellCornerRadius: CGFloat = 30
        public static let sidebarWidth: CGFloat = 246
        public static let sidebarPadding: CGFloat = 18
        public static let sidebarCornerRadius: CGFloat = 24
        public static let topBarHeight: CGFloat = 56
        public static let topBarCornerRadius: CGFloat = 18
        public static let panelCornerRadius: CGFloat = 22
        public static let subtlePanelCornerRadius: CGFloat = 20
        public static let metricCardCornerRadius: CGFloat = 18
        public static let cardInset: CGFloat = 18
        public static let navButtonCornerRadius: CGFloat = 12
        public static let navButtonHeight: CGFloat = 36
        public static let contentGap: CGFloat = 16
        public static let contentHorizontalPadding: CGFloat = 24
        public static let statusChipHeight: CGFloat = 30
        public static let loginCardWidth: CGFloat = 354
        public static let loginCardCornerRadius: CGFloat = 20
        public static let loginSegmentHeight: CGFloat = 34
        public static let buttonHeight: CGFloat = 38
        public static let iconButtonSize: CGFloat = 34
    }

    public enum Materials {
        public static let defaultGlassOpacity = 0.8
        public static let defaultBackgroundIntensity = 1.0
        public static let cardFillAlphaDark = 0.13
        public static let cardFillAlphaLight = 0.24
        public static let cardStrokeAlpha = 0.1
        public static let shellSurfaceFillAlphaDark = 0.16
        public static let shellSurfaceFillAlphaLight = 0.42
        public static let shellSurfaceStrokeAlpha = 0.16
        public static let topBarFillAlphaDark = 0.55
    }

    public enum Motion {
        public static let easeDuration = 0.3
        public static let hoverDuration = 0.2
        public static let pressDuration = 0.05
        public static let springResponse = 0.4
        public static let springDampingFraction = 0.9
    }

    public enum Typography {
        public static let heroTitleSize: CGFloat = 30
        public static let sectionTitleSize: CGFloat = 20
        public static let bodyTextSize: CGFloat = 13
        public static let captionTextSize: CGFloat = 11
        public static let navTitleSize: CGFloat = 15
        public static let navSubtitleSize: CGFloat = 10
        public static let pageTitleSize: CGFloat = 16
        public static let pageSubtitleSize: CGFloat = 12
        public static let loginHeroTitleSize: CGFloat = 28
        public static let loginSectionTitleSize: CGFloat = 22
        public static let buttonTextSize: CGFloat = 14
    }

    public enum Navigation {
        public static let primaryOrder = ["dashboard", "devices", "usb", "transfers", "remote", "monitor", "settings"]
        public static let secondaryOrder = ["recent", "profile", "login"]
    }

    public enum Palette {
        public static let windowGradientDark = ["#3B4F78", "#6F87B3", "#C4CEE3"].map(Color.init(hex:))
        public static let windowGradientLight = ["#FFFFFF", "#F0F4FC"].map(Color.init(hex:))
        public static let sidebarBackground = Color(hex: "#2E3857F0")
        public static let shellSurfaceFill = Color(hex: "#29FFFFFF")
        public static let shellSurfaceStroke = Color(hex: "#29FFFFFF")
        public static let topBarFill = Color(hex: "#8C47618F")
        public static let panelFillDark = Color(hex: "#21FFFFFF")
        public static let panelFillLight = Color(hex: "#3DFFFFFF")
        public static let panelStroke = Color(hex: "#1AFFFFFF")
        public static let metricCardFillDark = Color(hex: "#24FFFFFF")
        public static let metricCardFillLight = Color(hex: "#42FFFFFF")
        public static let rowFillDark = Color(hex: "#24000000")
        public static let loginCardFill = Color(hex: "#E0FFFFFF")
        public static let loginCardStroke = Color(hex: "#10000000")
        public static let inputFillLight = Color(hex: "#14000000")
        public static let accent = Color(hex: "#D93072EF")
        public static let accentPressed = Color(hex: "#D8205ED6")
        public static let success = Color(hex: "#FF4DC770")
        public static let warning = Color(hex: "#FFFF9A4D")
        public static let danger = Color(hex: "#FFFF5C5C")
        public static let textPrimaryDark = Color(hex: "#FFF7FAFF")
        public static let textSecondaryDark = Color(hex: "#B8FFFFFF")
        public static let textMutedDark = Color(hex: "#75FFFFFF")
        public static let textPrimaryLight = Color(hex: "#C7000000")
        public static let textSecondaryLight = Color(hex: "#6B000000")
        public static let textMutedLight = Color(hex: "#47000000")
        public static let selectedNavFill = Color(hex: "#D12368E0")
        public static let selectedNavIndicator = Color(hex: "#FFFFFFFF")
    }
}

private extension Color {
    init(hex: String) {
        let sanitized = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        let value = UInt64(sanitized, radix: 16) ?? 0
        let a, r, g, b: UInt64
        switch sanitized.count {
        case 8:
            a = (value & 0xFF00_0000) >> 24
            r = (value & 0x00FF_0000) >> 16
            g = (value & 0x0000_FF00) >> 8
            b = value & 0x0000_00FF
        case 6:
            a = 0xFF
            r = (value & 0xFF00_00) >> 16
            g = (value & 0x00FF_00) >> 8
            b = value & 0x0000_FF
        default:
            a = 0xFF
            r = 0
            g = 0
            b = 0
        }

        self.init(
            .sRGB,
            red: Double(r) / 255.0,
            green: Double(g) / 255.0,
            blue: Double(b) / 255.0,
            opacity: Double(a) / 255.0
        )
    }
}
