/* BoundSessionV1 product service C ABI -- generated by cbindgen. Do not edit. */
/*
 * All handles are opaque values issued by Rust. Copying a handle is allowed;
 * forging, cross-service reuse, reuse after destroy, and double completion fail closed.
 * Input and output regions in one call must be disjoint.
 */

#ifndef BOUND_SESSION_FFI_V1_H
#define BOUND_SESSION_FFI_V1_H

#pragma once

/* Generated; regenerate with: cbindgen --config cbindgen.toml --crate bound-session-ffi --output include/bound_session_ffi.h */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C ABI version implemented by this library.
 */
#define BS_FFI_ABI_VERSION_V1 1

/**
 * Additive evidence and trusted-delivery ABI version.
 */
#define BS_FFI_ABI_VERSION_V2 2

/**
 * Capability bit for enabled-only authoritative file-grant evidence.
 */
#define BS_FFI_CAPABILITY_GRANT_EVIDENCE_V2 (1 << 0)

/**
 * Capability bit for stable, non-destructive Ready/receipt peeks.
 */
#define BS_FFI_CAPABILITY_GRANT_OUTBOUND_PEEK_V2 (1 << 1)

/**
 * Capability bit for exact trusted-adapter delivery confirmation.
 */
#define BS_FFI_CAPABILITY_TRUSTED_DELIVERY_CONFIRMATION_V2 (1 << 2)

/**
 * Capability bit for authority-derived file-grant authorization installation.
 */
#define BS_FFI_CAPABILITY_DERIVED_FILE_GRANT_INSTALL_V2 (1 << 3)

/**
 * Exact additive capability set implemented by this binary.
 */
#define BS_FFI_CAPABILITIES_V2 (((BS_FFI_CAPABILITY_GRANT_EVIDENCE_V2 | BS_FFI_CAPABILITY_GRANT_OUTBOUND_PEEK_V2) | BS_FFI_CAPABILITY_TRUSTED_DELIVERY_CONFIRMATION_V2) | BS_FFI_CAPABILITY_DERIVED_FILE_GRANT_INSTALL_V2)

/**
 * Opaque service, owner, and session handle length.
 */
#define BS_FFI_HANDLE_BYTES_V1 24

/**
 * Maximum canonical context accepted at the ABI boundary.
 */
#define BS_FFI_MAX_CONTEXT_BYTES_V1 65535

/**
 * Maximum signed Q-Periapt policy document length.
 */
#define BS_FFI_MAX_SIGNED_POLICY_BYTES_V1 65536

/**
 * Persisted trusted Q-Periapt policy state length.
 */
#define BS_FFI_TRUSTED_POLICY_STATE_BYTES_V1 36

/**
 * ML-DSA-65 public verification key length.
 */
#define BS_FFI_ML_DSA_65_PUBLIC_KEY_BYTES_V1 1952

/**
 * ML-DSA-65 signature length.
 */
#define BS_FFI_ML_DSA_65_SIGNATURE_BYTES_V1 3309

/**
 * ML-KEM-768 expanded decapsulation key length.
 */
#define BS_FFI_ML_KEM_768_SECRET_KEY_BYTES_V1 2400

/**
 * ML-KEM-768 encapsulation key length.
 */
#define BS_FFI_ML_KEM_768_PUBLIC_KEY_BYTES_V1 1184

/**
 * X25519 secret/public key length.
 */
#define BS_FFI_X25519_KEY_BYTES_V1 32

/**
 * Message A exact pre-allocation maximum.
 */
#define BS_FFI_MESSAGE_A_MAX_BYTES_V1 5635

/**
 * Message B exact pre-allocation maximum.
 */
#define BS_FFI_MESSAGE_B_MAX_BYTES_V1 3821

/**
 * Finished exact pre-allocation maximum.
 */
#define BS_FFI_FINISHED_MAX_BYTES_V1 279

/**
 * GrantReady exact pre-allocation maximum.
 */
#define BS_FFI_GRANT_READY_MAX_BYTES_V1 193

/**
 * EffectReceipt exact pre-allocation maximum.
 */
#define BS_FFI_EFFECT_RECEIPT_MAX_BYTES_V1 492

/**
 * Largest outbound handshake, Ready, or receipt record supported by ABI v1.
 */
#define BS_FFI_MAX_OUTBOUND_BYTES_V1 5635

/**
 * Largest Ready or receipt record returned by the v2 grant peek.
 */
#define BS_FFI_GRANT_OUTBOUND_MAX_BYTES_V2 492

/**
 * Maximum requested V2 file-grant lifetime in process-monotonic milliseconds.
 */
#define BS_FFI_MAX_GRANT_AUTHORIZATION_LIFETIME_TICKS_V2 86400000

/**
 * Successful operation.
 */
#define BS_FFI_OK_V1 0

/**
 * A required pointer was null.
 */
#define BS_FFI_ERR_NULL_V1 -1

/**
 * A length, limit, or fixed-size field was invalid.
 */
#define BS_FFI_ERR_LENGTH_V1 -2

/**
 * ABI version or structure size mismatched.
 */
#define BS_FFI_ERR_ABI_V1 -3

/**
 * An output region overlapped an input or another output.
 */
#define BS_FFI_ERR_ALIASING_V1 -4

/**
 * The service handle was unknown, destroyed, or cross-instance.
 */
#define BS_FFI_ERR_INVALID_SERVICE_V1 -5

/**
 * The owner capability was unknown, revoked, or belonged to another service.
 */
#define BS_FFI_ERR_INVALID_OWNER_V1 -6

/**
 * The session handle was unknown, retired, or belonged to another service.
 */
#define BS_FFI_ERR_INVALID_SESSION_V1 -7

/**
 * The requested transition was invalid for the current typestate.
 */
#define BS_FFI_ERR_INVALID_STATE_V1 -8

/**
 * Signed-policy verification, rollback, or fixed-suite resolution failed.
 */
#define BS_FFI_ERR_POLICY_V1 -9

/**
 * Exact pinned identity verification failed.
 */
#define BS_FFI_ERR_IDENTITY_V1 -10

/**
 * Operating-system cryptographic entropy was unavailable.
 */
#define BS_FFI_ERR_ENTROPY_V1 -11

/**
 * Durable outbox construction or commit failed.
 */
#define BS_FFI_ERR_IO_V1 -12

/**
 * A configured bounded capacity was exhausted.
 */
#define BS_FFI_ERR_CAPACITY_V1 -13

/**
 * The handshake lifetime expired.
 */
#define BS_FFI_ERR_EXPIRED_V1 -14

/**
 * A caller output buffer was smaller than the reported exact requirement.
 */
#define BS_FFI_ERR_BUFFER_TOO_SMALL_V1 -15

/**
 * The requested production durability contract is unavailable on this target.
 */
#define BS_FFI_ERR_UNSUPPORTED_V1 -16

/**
 * Canonical decoding, transcript binding, or peer authentication failed.
 */
#define BS_FFI_ERR_PROTOCOL_V1 -17

/**
 * A panic was caught before it could cross the C ABI.
 */
#define BS_FFI_ERR_PANIC_V1 -18

/**
 * A non-public internal invariant or provider failure occurred.
 */
#define BS_FFI_ERR_INTERNAL_V1 -19

/**
 * An exact owner or peer-session identity was already live.
 */
#define BS_FFI_ERR_DUPLICATE_V1 -20

/**
 * No outbound record is pending for the session.
 */
#define BS_FFI_ERR_NO_OUTPUT_V1 -21

/**
 * Supplied recipient or identity key material was inconsistent.
 */
#define BS_FFI_ERR_KEY_MISMATCH_V1 -22

/**
 * The grant handle was unknown, retired, stale, or cross-instance.
 */
#define BS_FFI_ERR_INVALID_GRANT_V1 -23

/**
 * The operation handle was unknown, consumed, stale, or cross-instance.
 */
#define BS_FFI_ERR_INVALID_OPERATION_V1 -24

/**
 * The commit-permit handle was unknown, consumed, stale, or cross-instance.
 */
#define BS_FFI_ERR_INVALID_PERMIT_V1 -25

/**
 * The finalization-retry handle was unknown, consumed, stale, or cross-instance.
 */
#define BS_FFI_ERR_INVALID_RETRY_V1 -26

/**
 * Initiator role code in a signature request.
 */
#define BS_FFI_ROLE_INITIATOR_V1 1

/**
 * Responder role code in a signature request.
 */
#define BS_FFI_ROLE_RESPONDER_V1 2

/**
 * Message A record kind code.
 */
#define BS_FFI_RECORD_MESSAGE_A_V1 7

/**
 * Message B record kind code.
 */
#define BS_FFI_RECORD_MESSAGE_B_V1 8

/**
 * Finished record kind code.
 */
#define BS_FFI_RECORD_FINISHED_V1 9

/**
 * GrantReady record kind code.
 */
#define BS_FFI_RECORD_GRANT_READY_V1 4

/**
 * EffectReceipt record kind code.
 */
#define BS_FFI_RECORD_EFFECT_RECEIPT_V1 5

/**
 * Awaiting initiator Message A signature.
 */
#define BS_FFI_STATE_AWAITING_MESSAGE_A_SIGNATURE_V1 1

/**
 * Awaiting authenticated Message B.
 */
#define BS_FFI_STATE_AWAITING_MESSAGE_B_V1 2

/**
 * Awaiting responder Finished.
 */
#define BS_FFI_STATE_AWAITING_RESPONDER_FINISHED_V1 3

/**
 * Awaiting responder Message B signature.
 */
#define BS_FFI_STATE_AWAITING_MESSAGE_B_SIGNATURE_V1 4

/**
 * Awaiting initiator Finished.
 */
#define BS_FFI_STATE_AWAITING_INITIATOR_FINISHED_V1 5

/**
 * Both Finished records authenticated; root remains opaque in Rust.
 */
#define BS_FFI_STATE_ESTABLISHED_V1 6

/**
 * Terminally failed until explicit abort.
 */
#define BS_FFI_STATE_FAILED_V1 7

/**
 * Enable call performed the first transition to Enabled.
 */
#define BS_FFI_ENABLE_FIRST_V1 1

/**
 * Enable call was an exact replay of an already-enabled grant.
 */
#define BS_FFI_ENABLE_EXACT_REPLAY_V1 2

/**
 * Peer receipt was accepted for the first time.
 */
#define BS_FFI_RECEIPT_FIRST_ACCEPTED_V1 1

/**
 * Peer receipt was an exact authenticated replay.
 */
#define BS_FFI_RECEIPT_EXACT_REPLAY_V1 2

/**
 * Trusted durable-file adapter reports a committed effect.
 */
#define BS_FFI_FINALIZE_COMMITTED_V1 1

/**
 * Trusted durable-file adapter reports an ambiguous effect.
 */
#define BS_FFI_FINALIZE_AMBIGUOUS_V1 2

/**
 * Finalization queued a canonical receipt in the grant outbox.
 */
#define BS_FFI_FINALIZATION_RECEIPT_QUEUED_V1 1

/**
 * Finalization retained the exact sealed request for retry.
 */
#define BS_FFI_FINALIZATION_RETRY_REQUIRED_V1 2

/**
 * Initiator-to-responder file or record direction in ABI v2 metadata.
 */
#define BS_FFI_DIRECTION_INITIATOR_TO_RESPONDER_V2 1

/**
 * Responder-to-initiator file or record direction in ABI v2 metadata.
 */
#define BS_FFI_DIRECTION_RESPONDER_TO_INITIATOR_V2 2

/**
 * The projected grant is currently enabled.
 */
#define BS_FFI_GRANT_STATE_ENABLED_V2 1

/**
 * The local endpoint has no durable-file target scope for this grant.
 */
#define BS_FFI_TARGET_SCOPE_ABSENT_V2 0

/**
 * The local endpoint has one authority-bound durable-file target scope.
 */
#define BS_FFI_TARGET_SCOPE_PRESENT_V2 1

/**
 * This call first confirmed the exact current outbound record.
 */
#define BS_FFI_DELIVERY_FIRST_CONFIRMED_V2 1

/**
 * This call exactly replayed the immediately preceding confirmation.
 */
#define BS_FFI_DELIVERY_CONFIRMATION_EXACT_REPLAY_V2 2

/**
 * Borrowed immutable byte region supplied by the host for one call.
 */
typedef struct {
    /**
     * Readable start address.
     */
    const uint8_t *pointer;
    /**
     * Number of readable bytes.
     */
    uintptr_t length;
} BsFfiBytesV1;

/**
 * Sealed production factory configuration.
 */
typedef struct {
    /**
     * Must equal [`BS_FFI_ABI_VERSION_V1`].
     */
    uint32_t abi_version;
    /**
     * Must equal `sizeof(BsFfiServiceConfigV1)`.
     */
    uint32_t struct_size;
    /**
     * Maximum simultaneously retained handshakes.
     */
    uint32_t max_in_flight_sessions;
    /**
     * Maximum simultaneously issued owner capabilities.
     */
    uint32_t max_owner_capabilities;
    /**
     * Maximum process-monotonic handshake lifetime, in milliseconds.
     */
    uint64_t max_handshake_lifetime_ticks;
    /**
     * Exact signed Q-Periapt policy bytes.
     */
    BsFfiBytesV1 signed_policy;
    /**
     * Detached ML-DSA-65 signature over the signed policy.
     */
    BsFfiBytesV1 policy_signature;
    /**
     * Pinned ML-DSA-65 policy-root verification key.
     */
    BsFfiBytesV1 policy_verification_key;
    /**
     * Empty for enrollment, otherwise the exact 36-byte last trusted state.
     */
    BsFfiBytesV1 last_trusted_policy_state;
    /**
     * Local expanded ML-KEM-768 recipient secret key; copied into a zeroizing Rust owner.
     */
    BsFfiBytesV1 local_recipient_pq_secret_key;
    /**
     * Local ML-KEM-768 recipient public key paired with the local secret.
     */
    BsFfiBytesV1 local_recipient_pq_public_key;
    /**
     * Local X25519 recipient secret key; copied into a zeroizing Rust owner.
     */
    BsFfiBytesV1 local_recipient_x25519_secret_key;
    /**
     * Local X25519 recipient public key paired with the local secret.
     */
    BsFfiBytesV1 local_recipient_x25519_public_key;
    /**
     * Peer ML-KEM-768 recipient public key. No peer recipient secret is accepted.
     */
    BsFfiBytesV1 peer_recipient_pq_public_key;
    /**
     * Peer X25519 recipient public key. No peer recipient secret is accepted.
     */
    BsFfiBytesV1 peer_recipient_x25519_public_key;
    /**
     * Exact pinned local ML-DSA-65 identity verification key.
     */
    BsFfiBytesV1 local_identity_verification_key;
    /**
     * Exact pinned peer ML-DSA-65 identity verification key.
     */
    BsFfiBytesV1 peer_identity_verification_key;
    /**
     * Absolute, existing, private directory used for durable Finished records.
     */
    BsFfiBytesV1 finished_outbox_root;
    /**
     * Must be all zero for ABI v1.
     */
    uint8_t reserved[16];
} BsFfiServiceConfigV1;

/**
 * Opaque Rust-issued service handle.
 */
typedef struct {
    /**
     * Opaque bytes; callers must not derive or reinterpret them.
     */
    uint8_t opaque[BS_FFI_HANDLE_BYTES_V1];
} BsFfiServiceHandleV1;

/**
 * Public, non-secret metadata returned only after complete factory validation.
 */
typedef struct {
    /**
     * ABI version of this output structure.
     */
    uint32_t abi_version;
    /**
     * `sizeof(BsFfiServiceCreateResultV1)`.
     */
    uint32_t struct_size;
    /**
     * Rust-issued service handle.
     */
    BsFfiServiceHandleV1 service;
    /**
     * Trusted policy state that the host must persist monotonically.
     */
    uint8_t trusted_policy_state[BS_FFI_TRUSTED_POLICY_STATE_BYTES_V1];
    /**
     * Fingerprint of the authenticated policy-root verification key.
     */
    uint8_t policy_root_fingerprint[32];
    /**
     * Digest of the exact local recipient ML-KEM/X25519 public keys.
     */
    uint8_t local_recipient_key_digest[32];
    /**
     * Digest of the exact peer recipient ML-KEM/X25519 public keys.
     */
    uint8_t peer_recipient_key_digest[32];
    /**
     * Exact local identity fingerprint.
     */
    uint8_t local_identity_fingerprint[32];
    /**
     * Exact peer identity fingerprint.
     */
    uint8_t peer_identity_fingerprint[32];
} BsFfiServiceCreateResultV1;

/**
 * Trusted host input from which Rust issues an opaque owner capability.
 */
typedef struct {
    /**
     * Must equal [`BS_FFI_ABI_VERSION_V1`].
     */
    uint32_t abi_version;
    /**
     * Must equal `sizeof(BsFfiOwnerInputV1)`.
     */
    uint32_t struct_size;
    /**
     * Digest of the authenticated local caller principal.
     */
    uint8_t caller_principal_digest[32];
    /**
     * Non-zero product connection generation.
     */
    uint64_t connection_generation;
    /**
     * Non-network operation token.
     */
    uint8_t operation_token[32];
    /**
     * Digest of the exact product driver identity.
     */
    uint8_t driver_identity_digest[32];
    /**
     * Non-network arbiter lease.
     */
    uint8_t arbiter_lease[32];
    /**
     * Non-zero local policy-decision epoch.
     */
    uint64_t decision_epoch;
    /**
     * Must be all zero for ABI v1.
     */
    uint8_t reserved[16];
} BsFfiOwnerInputV1;

/**
 * Opaque Rust-issued outer-owner capability.
 */
typedef struct {
    /**
     * Opaque bytes; callers must not derive or reinterpret them.
     */
    uint8_t opaque[BS_FFI_HANDLE_BYTES_V1];
} BsFfiOwnerHandleV1;

/**
 * Opaque Rust-issued handshake-session handle.
 */
typedef struct {
    /**
     * Opaque bytes; callers must not derive or reinterpret them.
     */
    uint8_t opaque[BS_FFI_HANDLE_BYTES_V1];
} BsFfiSessionHandleV1;

/**
 * Exact, non-secret asynchronous identity-signing request.
 */
typedef struct {
    /**
     * ABI version of this output structure.
     */
    uint32_t abi_version;
    /**
     * `sizeof(BsFfiSignatureRequestV1)`.
     */
    uint32_t struct_size;
    /**
     * Rust-issued session handle to resume exactly once.
     */
    BsFfiSessionHandleV1 session;
    /**
     * [`BS_FFI_ROLE_INITIATOR_V1`] or [`BS_FFI_ROLE_RESPONDER_V1`].
     */
    uint32_t role;
    /**
     * Exact pinned identity fingerprint selected by stored typestate.
     */
    uint8_t identity_fingerprint[32];
    /**
     * Exact 32-byte domain-separated signature preimage selected by Rust.
     */
    uint8_t preimage[32];
} BsFfiSignatureRequestV1;

/**
 * Non-secret established-session binding snapshot.
 */
typedef struct {
    /**
     * ABI version of this output structure.
     */
    uint32_t abi_version;
    /**
     * `sizeof(BsFfiEstablishedInfoV1)`.
     */
    uint32_t struct_size;
    /**
     * Exact peer-session identifier.
     */
    uint8_t peer_session_id[32];
    /**
     * Digest of the canonical full context.
     */
    uint8_t context_digest[32];
    /**
     * Digest of authenticated Message A and Message B.
     */
    uint8_t transcript_digest[32];
} BsFfiEstablishedInfoV1;

/**
 * Trusted local authorization input for installing one file-purpose grant.
 */
typedef struct {
    /**
     * Must equal [`BS_FFI_ABI_VERSION_V1`].
     */
    uint32_t abi_version;
    /**
     * Must equal `sizeof(BsFfiFileGrantAuthorizationV1)`.
     */
    uint32_t struct_size;
    /**
     * [`BS_FFI_ROLE_INITIATOR_V1`] or [`BS_FFI_ROLE_RESPONDER_V1`].
     */
    uint32_t local_role;
    /**
     * Non-zero endpoint-private authorization commitment.
     */
    uint8_t local_authorization_commitment[32];
    /**
     * Non-zero endpoint-private authorization transaction identifier.
     */
    uint8_t authorization_transaction_id[32];
    /**
     * Non-zero monotonic grant deadline.
     */
    uint64_t expires_at_tick;
    /**
     * Receiver-only non-zero sealed target scope; sender must supply all zero.
     */
    uint8_t receiver_target_scope_digest[32];
    /**
     * Must be all zero for ABI v1.
     */
    uint8_t reserved[16];
} BsFfiFileGrantAuthorizationV1;

/**
 * Opaque Rust-issued file-grant handle.
 */
typedef struct {
    /**
     * Opaque random bytes; callers must not derive or reinterpret them.
     */
    uint8_t opaque[BS_FFI_HANDLE_BYTES_V1];
} BsFfiGrantHandleV1;

/**
 * Result of retiring a handshake into a fresh file grant.
 */
typedef struct {
    /**
     * ABI version of this output structure.
     */
    uint32_t abi_version;
    /**
     * `sizeof(BsFfiFileGrantInstallResultV1)`.
     */
    uint32_t struct_size;
    /**
     * Fresh Rust-issued grant handle.
     */
    BsFfiGrantHandleV1 grant;
    /**
     * Exact peer-session identifier.
     */
    uint8_t peer_session_id[32];
    /**
     * Authenticated local role.
     */
    uint32_t local_role;
    /**
     * One when this endpoint is the file receiver, otherwise zero.
     */
    uint32_t local_receives_file;
} BsFfiFileGrantInstallResultV1;

/**
 * Trusted platform evidence used by Rust to derive a file-grant authorization.
 *
 * The caller supplies only a public platform-evidence digest, a bounded
 * lifetime, and the receiver-only target scope. Rust derives the absolute
 * service-clock expiry and canonical local record, then generates the private
 * grant id, authorization transaction id, and commitment nonce.
 */
typedef struct {
    /**
     * Must equal [`BS_FFI_ABI_VERSION_V2`].
     */
    uint32_t abi_version;
    /**
     * Must equal `sizeof(BsFfiDerivedFileGrantAuthorizationV2)`.
     */
    uint32_t struct_size;
    /**
     * Whether `receiver_target_scope_digest` is present.
     */
    uint32_t receiver_target_scope_presence;
    /**
     * Must be zero.
     */
    uint32_t reserved_u32;
    /**
     * Non-zero bounded lifetime; Rust derives the absolute service-clock expiry.
     */
    uint64_t authorization_lifetime_ticks;
    /**
     * Non-zero public digest of trusted platform authorization evidence.
     */
    uint8_t platform_authorization_evidence_digest[32];
    /**
     * Receiver-only non-zero target scope, or all zero when absent.
     */
    uint8_t receiver_target_scope_digest[32];
    /**
     * Must be all zero.
     */
    uint8_t reserved[16];
} BsFfiDerivedFileGrantAuthorizationV2;

/**
 * Result of retiring a handshake through Rust-derived authorization.
 */
typedef struct {
    /**
     * Must equal [`BS_FFI_ABI_VERSION_V2`] on success.
     */
    uint32_t abi_version;
    /**
     * `sizeof(BsFfiFileGrantInstallResultV2)`.
     */
    uint32_t struct_size;
    /**
     * Fresh Rust-issued grant handle.
     */
    BsFfiGrantHandleV1 grant;
    /**
     * Exact peer-session identifier.
     */
    uint8_t peer_session_id[32];
    /**
     * Authenticated local role.
     */
    uint32_t local_role;
    /**
     * One when this endpoint is the file receiver, otherwise zero.
     */
    uint32_t local_receives_file;
} BsFfiFileGrantInstallResultV2;

/**
 * Result of first-enable versus exact replay.
 */
typedef struct {
    /**
     * ABI version of this output structure.
     */
    uint32_t abi_version;
    /**
     * `sizeof(BsFfiGrantEnableResultV1)`.
     */
    uint32_t struct_size;
    /**
     * [`BS_FFI_ENABLE_FIRST_V1`] or [`BS_FFI_ENABLE_EXACT_REPLAY_V1`].
     */
    uint32_t outcome;
    /**
     * Digest of the role-ordered bilateral Ready set.
     */
    uint8_t bilateral_ready_digest[32];
} BsFfiGrantEnableResultV1;

/**
 * Enabled-only authoritative file-grant evidence for ABI v2.
 *
 * Every security-critical field is projected from Rust authority/service state;
 * this projection call cannot override any output field. Some sealed inputs
 * originated at the trusted platform adapter when the grant was installed.
 * Local correlation digests are not signatures, peer provenance, executable
 * identity, or attestation.
 */
typedef struct {
    /**
     * Must equal [`BS_FFI_ABI_VERSION_V2`] on success.
     */
    uint32_t abi_version;
    /**
     * `sizeof(BsFfiFileGrantEvidenceV2)`.
     */
    uint32_t struct_size;
    /**
     * Always [`BS_FFI_GRANT_STATE_ENABLED_V2`] for a successful projection.
     */
    uint32_t grant_state;
    /**
     * Canonical file-purpose direction.
     */
    uint32_t file_direction;
    /**
     * Local protocol role.
     */
    uint32_t local_role;
    /**
     * One only when the canonical direction makes this endpoint the receiver.
     */
    uint32_t local_receives_file;
    /**
     * Whether `local_durable_file_target_scope` is present.
     */
    uint32_t local_durable_file_target_scope_presence;
    /**
     * Reserved alignment field; zero on output.
     */
    uint32_t reserved_u32;
    /**
     * Exact product connection generation from the sealed owner binding.
     */
    uint64_t connection_generation;
    /**
     * Exact decision epoch bound to the owner and grant.
     */
    uint64_t decision_epoch;
    /**
     * Exact grant deadline in this service incarnation's monotonic clock domain.
     */
    uint64_t authorization_expires_at_tick;
    /**
     * Authenticated Q-Periapt policy version.
     */
    uint64_t policy_version;
    /**
     * Canonical file byte count.
     */
    uint64_t declared_bytes;
    /**
     * Bound wire-crypto profile identifier.
     */
    uint32_t wire_crypto_profile_id;
    /**
     * Bound Q-Periapt suite identifier.
     */
    uint32_t suite_id;
    /**
     * Bound hybrid profile identifier.
     */
    uint32_t hybrid_profile_id;
    /**
     * Bound recipient-key format identifier.
     */
    uint32_t key_format_id;
    /**
     * Exact peer-session identifier.
     */
    uint8_t peer_session_id[32];
    /**
     * Canonical full-context digest.
     */
    uint8_t context_digest[32];
    /**
     * Authenticated Message A/B transcript digest.
     */
    uint8_t transcript_digest[32];
    /**
     * Authority-derived shared grant identifier.
     */
    uint8_t shared_grant_id[32];
    /**
     * Role-ordered bilateral Ready digest.
     */
    uint8_t bilateral_ready_digest[32];
    /**
     * Authenticated Q-Periapt policy digest.
     */
    uint8_t policy_digest[32];
    /**
     * Authenticated policy-root fingerprint.
     */
    uint8_t policy_root_key_fingerprint[32];
    /**
     * Digest of the complete authenticated wire decision.
     */
    uint8_t wire_decision_digest[32];
    /**
     * Canonical file-purpose digest.
     */
    uint8_t purpose_digest[32];
    /**
     * Bound recipient ML-KEM/X25519 public-key digest.
     */
    uint8_t recipient_kem_public_key_digest[32];
    /**
     * Authenticated initiator identity fingerprint.
     */
    uint8_t initiator_identity_fingerprint[32];
    /**
     * Authenticated responder identity fingerprint.
     */
    uint8_t responder_identity_fingerprint[32];
    /**
     * Canonical client nonce.
     */
    uint8_t client_nonce[32];
    /**
     * Canonical independent 32-byte transfer identifier.
     */
    uint8_t transfer_id[32];
    /**
     * Canonical file-content SHA-256.
     */
    uint8_t content_sha256[32];
    /**
     * Exact local authorization commitment stored by the authority.
     */
    uint8_t local_authorization_commitment[32];
    /**
     * Receiver-only target scope, or all zero when presence is absent.
     */
    uint8_t local_durable_file_target_scope[32];
    /**
     * Domain-separated digest of the endpoint-private authorization transaction.
     */
    uint8_t authorization_transaction_id_digest[32];
    /**
     * Public trusted-adapter evidence digest bound into the local record.
     */
    uint8_t platform_authorization_evidence_digest[32];
    /**
     * Rust-derived canonical local authorization-record digest.
     */
    uint8_t authorization_record_digest[32];
    /**
     * Domain-separated digest of the complete local owner tuple and epoch.
     */
    uint8_t owner_binding_digest[32];
    /**
     * Domain-separated digest of the Rust-issued service incarnation.
     */
    uint8_t service_incarnation_digest[32];
    /**
     * Fixed trusted durable-file committer registration identity.
     */
    uint8_t durable_file_committer_identity_digest[32];
} BsFfiFileGrantEvidenceV2;

/**
 * Stable metadata for one non-destructively peeked Ready or receipt.
 */
typedef struct {
    /**
     * Must equal [`BS_FFI_ABI_VERSION_V2`] on success.
     */
    uint32_t abi_version;
    /**
     * `sizeof(BsFfiGrantOutboundMetadataV2)`.
     */
    uint32_t struct_size;
    /**
     * Exact canonical Ready or EffectReceipt structure kind.
     */
    uint32_t record_kind;
    /**
     * Authenticated record direction derived from the local issuer role.
     */
    uint32_t record_direction;
    /**
     * Exact record byte length.
     */
    uint64_t record_length;
    /**
     * Ready sequence or receipt monotonic sequence decoded from exact bytes.
     */
    uint64_t logical_sequence;
    /**
     * Deterministic domain-separated identifier independently recomputable by a peer.
     */
    uint8_t record_id[32];
    /**
     * SHA-256 of the exact canonical record bytes.
     */
    uint8_t record_sha256[32];
    /**
     * Exact peer-session identifier decoded and cross-checked by Rust.
     */
    uint8_t peer_session_id[32];
    /**
     * Exact shared grant identifier decoded and cross-checked by Rust.
     */
    uint8_t shared_grant_id[32];
} BsFfiGrantOutboundMetadataV2;

/**
 * Exact trusted-adapter delivery confirmation input.
 */
typedef struct {
    /**
     * Must equal [`BS_FFI_ABI_VERSION_V2`].
     */
    uint32_t abi_version;
    /**
     * Must equal `sizeof(BsFfiTrustedDeliveryConfirmationInputV2)`.
     */
    uint32_t struct_size;
    /**
     * Identifier returned by the current exact peek.
     */
    uint8_t record_id[32];
    /**
     * Exact record SHA-256 returned by the current exact peek.
     */
    uint8_t record_sha256[32];
    /**
     * Must be all zero.
     */
    uint8_t reserved[16];
} BsFfiTrustedDeliveryConfirmationInputV2;

/**
 * Result of confirming trusted-adapter delivery of one exact record.
 */
typedef struct {
    /**
     * Must equal [`BS_FFI_ABI_VERSION_V2`] on success.
     */
    uint32_t abi_version;
    /**
     * `sizeof(BsFfiTrustedDeliveryConfirmationResultV2)`.
     */
    uint32_t struct_size;
    /**
     * First confirmation or immediate exact replay.
     */
    uint32_t outcome;
    /**
     * Must be zero.
     */
    uint32_t reserved;
} BsFfiTrustedDeliveryConfirmationResultV2;

/**
 * Canonical non-secret authenticated file-operation descriptor.
 */
typedef struct {
    /**
     * ABI version of this structure.
     */
    uint32_t abi_version;
    /**
     * `sizeof(BsFfiFileOperationDescriptorV1)`.
     */
    uint32_t struct_size;
    /**
     * Rust-generated non-zero authority operation identifier.
     */
    uint8_t operation_id[32];
    /**
     * Non-zero per-peer monotonic sequence.
     */
    uint64_t sequence;
    /**
     * Non-zero digest supplied by the authenticated transport adapter.
     */
    uint8_t request_digest[32];
} BsFfiFileOperationDescriptorV1;

/**
 * Opaque Rust-issued reserved-operation handle.
 */
typedef struct {
    /**
     * Opaque random bytes; callers must not derive or reinterpret them.
     */
    uint8_t opaque[BS_FFI_HANDLE_BYTES_V1];
} BsFfiOperationHandleV1;

/**
 * Opaque Rust-issued may-have-started permit handle.
 */
typedef struct {
    /**
     * Opaque random bytes; callers must not derive or reinterpret them.
     */
    uint8_t opaque[BS_FFI_HANDLE_BYTES_V1];
} BsFfiCommitPermitHandleV1;

/**
 * Opaque Rust-issued sealed-finalization retry handle.
 */
typedef struct {
    /**
     * Opaque random bytes; callers must not derive or reinterpret them.
     */
    uint8_t opaque[BS_FFI_HANDLE_BYTES_V1];
} BsFfiFinalizationRetryHandleV1;

/**
 * Result of durable-file receipt finalization.
 */
typedef struct {
    /**
     * ABI version of this output structure.
     */
    uint32_t abi_version;
    /**
     * `sizeof(BsFfiFileFinalizationResultV1)`.
     */
    uint32_t struct_size;
    /**
     * Receipt queued or exact sealed retry required.
     */
    uint32_t outcome;
    /**
     * Non-zero only when `outcome` is retry-required.
     */
    BsFfiFinalizationRetryHandleV1 retry;
} BsFfiFileFinalizationResultV1;

/**
 * Return the linked C ABI version.
 */
uint32_t bs_ffi_abi_version_v1(void);

/**
 * Return the exact additive ABI-v2 capability bitmap.
 */
uint64_t bs_ffi_capabilities_v2(void);

/**
 * Return a stable NUL-terminated ASCII status name.
 */
const char *bs_ffi_status_name_v1(int32_t status);

/**
 * Create a production service using only the sealed provider/verifier/outbox stack.
 *
 * # Safety
 * `config` must be readable for one complete configuration structure. Every configured
 * byte region must be readable for its declared length. `out_result` must be writable for
 * one result structure. The output must not overlap the configuration or any input region.
 */
int32_t bs_ffi_service_create_v1(const BsFfiServiceConfigV1 *config,
                                 BsFfiServiceCreateResultV1 *out_result);

/**
 * Destroy a service and all retained owners, sessions, roots, and provider key owners.
 */
int32_t bs_ffi_service_destroy_v1(BsFfiServiceHandleV1 service);

/**
 * Issue an opaque owner capability from a trusted host binding.
 *
 * # Safety
 * `input` must be readable for one owner-input structure and `out_owner` writable for one
 * owner handle. The regions must not overlap.
 */
int32_t bs_ffi_owner_issue_v1(BsFfiServiceHandleV1 service,
                              const BsFfiOwnerInputV1 *input,
                              BsFfiOwnerHandleV1 *out_owner);

/**
 * Revoke an owner and abort every handshake bound to it.
 */
int32_t bs_ffi_owner_destroy_v1(BsFfiServiceHandleV1 service, BsFfiOwnerHandleV1 owner);

/**
 * Start an initiator handshake and return its exact asynchronous signature request.
 *
 * # Safety
 * `context` must be readable for `context_len`; `out_request` must be writable for one
 * request and must not overlap the context.
 */
int32_t bs_ffi_session_begin_initiator_v1(BsFfiServiceHandleV1 service,
                                          BsFfiOwnerHandleV1 owner,
                                          const uint8_t *context,
                                          uintptr_t context_len,
                                          BsFfiSignatureRequestV1 *out_request);

/**
 * Authenticate Message A, perform responder decapsulation, and return the exact Message B
 * signature request. Authentication occurs before the official provider is invoked.
 *
 * # Safety
 * All input regions must be readable for their lengths. `out_request` must be writable for one
 * request and disjoint from every input.
 */
int32_t bs_ffi_session_accept_message_a_v1(BsFfiServiceHandleV1 service,
                                           BsFfiOwnerHandleV1 owner,
                                           const uint8_t *context,
                                           uintptr_t context_len,
                                           const uint8_t *message_a,
                                           uintptr_t message_a_len,
                                           const uint8_t *responder_nonce,
                                           uintptr_t responder_nonce_len,
                                           BsFfiSignatureRequestV1 *out_request);

/**
 * Resume one stored signing pause with exactly one ML-DSA-65 signature.
 *
 * # Safety
 * `signature` must be readable for exactly [`BS_FFI_ML_DSA_65_SIGNATURE_BYTES_V1`] bytes.
 */
int32_t bs_ffi_session_complete_signature_v1(BsFfiServiceHandleV1 service,
                                             BsFfiOwnerHandleV1 owner,
                                             BsFfiSessionHandleV1 session,
                                             const uint8_t *signature,
                                             uintptr_t signature_len);

/**
 * Authenticate Message B and retain the exact initiator Finished as pending outbound data.
 *
 * # Safety
 * `message_b` must be readable for `message_b_len` bytes.
 */
int32_t bs_ffi_session_accept_message_b_v1(BsFfiServiceHandleV1 service,
                                           BsFfiOwnerHandleV1 owner,
                                           BsFfiSessionHandleV1 session,
                                           const uint8_t *message_b,
                                           uintptr_t message_b_len);

/**
 * Authenticate initiator Finished, durably commit responder Finished, and retain it pending.
 *
 * # Safety
 * `finished` must be readable for `finished_len` bytes.
 */
int32_t bs_ffi_session_accept_initiator_finished_v1(BsFfiServiceHandleV1 service,
                                                    BsFfiOwnerHandleV1 owner,
                                                    BsFfiSessionHandleV1 session,
                                                    const uint8_t *finished,
                                                    uintptr_t finished_len);

/**
 * Authenticate responder Finished and retain only opaque Established state plus public digests.
 *
 * # Safety
 * `finished` must be readable for `finished_len` bytes.
 */
int32_t bs_ffi_session_accept_responder_finished_v1(BsFfiServiceHandleV1 service,
                                                    BsFfiOwnerHandleV1 owner,
                                                    BsFfiSessionHandleV1 session,
                                                    const uint8_t *finished,
                                                    uintptr_t finished_len);

/**
 * Apply the current typestate's exact declared-length cap before carrier allocation.
 */
int32_t bs_ffi_session_validate_inbound_length_v1(BsFfiServiceHandleV1 service,
                                                  BsFfiOwnerHandleV1 owner,
                                                  BsFfiSessionHandleV1 session,
                                                  uint32_t record_kind,
                                                  uintptr_t declared_length);

/**
 * Return the static exact maximum for a wire record kind.
 *
 * # Safety
 * `out_maximum` must be writable for one `size_t`.
 */
int32_t bs_ffi_wire_max_length_v1(uint32_t record_kind, uintptr_t *out_maximum);

/**
 * Return the exact pending outbound kind and byte count without consuming it.
 *
 * # Safety
 * Both outputs must be writable and disjoint.
 */
int32_t bs_ffi_session_outbound_size_v1(BsFfiServiceHandleV1 service,
                                        BsFfiOwnerHandleV1 owner,
                                        BsFfiSessionHandleV1 session,
                                        uint32_t *out_record_kind,
                                        uintptr_t *out_length);

/**
 * Copy and consume one exact pending outbound record.
 *
 * Call [`bs_ffi_session_outbound_size_v1`] first. On `ERR_BUFFER_TOO_SMALL`, this function
 * writes the exact required length and kind but leaves the pending record intact.
 *
 * # Safety
 * `out_bytes` must be writable for `out_capacity`; the scalar outputs must each be writable.
 * All three output regions must be pairwise disjoint.
 */
int32_t bs_ffi_session_take_outbound_v1(BsFfiServiceHandleV1 service,
                                        BsFfiOwnerHandleV1 owner,
                                        BsFfiSessionHandleV1 session,
                                        uint8_t *out_bytes,
                                        uintptr_t out_capacity,
                                        uint32_t *out_record_kind,
                                        uintptr_t *out_length);

/**
 * Return the current public session-state code.
 *
 * # Safety
 * `out_state` must be writable for one `uint32_t`.
 */
int32_t bs_ffi_session_state_v1(BsFfiServiceHandleV1 service,
                                BsFfiOwnerHandleV1 owner,
                                BsFfiSessionHandleV1 session,
                                uint32_t *out_state);

/**
 * Return non-secret established binding metadata; never returns a root or key.
 *
 * # Safety
 * `out_info` must be writable for one complete established-info structure.
 */
int32_t bs_ffi_session_established_info_v1(BsFfiServiceHandleV1 service,
                                           BsFfiOwnerHandleV1 owner,
                                           BsFfiSessionHandleV1 session,
                                           BsFfiEstablishedInfoV1 *out_info);

/**
 * Abort a session and destroy every retained secret-bearing typestate.
 */
int32_t bs_ffi_session_abort_v1(BsFfiServiceHandleV1 service,
                                BsFfiOwnerHandleV1 owner,
                                BsFfiSessionHandleV1 session);

/**
 * Retire an established handshake into a fresh canonical file-purpose grant.
 *
 * # Safety
 * `authorization` must be readable and `out_result` writable for their full
 * structures. They must not overlap.
 */
int32_t bs_ffi_session_install_file_grant_v1(BsFfiServiceHandleV1 service,
                                             BsFfiOwnerHandleV1 owner,
                                             BsFfiSessionHandleV1 session,
                                             const BsFfiFileGrantAuthorizationV1 *authorization,
                                             BsFfiFileGrantInstallResultV1 *out_result);

/**
 * Retire an established handshake through Rust-derived file authorization.
 *
 * The host supplies only a public platform-evidence digest, a monotonic
 * lifetime, and the receiver-only target scope. Rust derives the exact local
 * role and shared grant from the established session, derives a canonical
 * authorization-record digest that binds those values to the exact owner,
 * and generates/seals the private commitment opening with OS entropy. This
 * function never falls back to the legacy v1 installation path.
 *
 * # Safety
 * `authorization` must be readable and `out_result` writable for their full
 * structures. They must not overlap.
 */
int32_t bs_ffi_session_install_file_grant_v2(BsFfiServiceHandleV1 service,
                                             BsFfiOwnerHandleV1 owner,
                                             BsFfiSessionHandleV1 session,
                                             const BsFfiDerivedFileGrantAuthorizationV2 *authorization,
                                             BsFfiFileGrantInstallResultV2 *out_result);

/**
 * Commit the exact local authorization stored during grant installation.
 */
int32_t bs_ffi_grant_commit_authorization_v1(BsFfiServiceHandleV1 service,
                                             BsFfiOwnerHandleV1 owner,
                                             BsFfiGrantHandleV1 grant);

/**
 * Ask the authority to generate and queue its sole local signed Ready.
 */
int32_t bs_ffi_grant_prepare_local_ready_v1(BsFfiServiceHandleV1 service,
                                            BsFfiOwnerHandleV1 owner,
                                            BsFfiGrantHandleV1 grant);

/**
 * Authenticate peer Ready, then perform first-enable or exact replay.
 *
 * # Safety
 * `encoded_ready` must be readable and `out_result` writable for the declared
 * lengths; the regions must not overlap.
 */
int32_t bs_ffi_grant_accept_peer_ready_enable_v1(BsFfiServiceHandleV1 service,
                                                 BsFfiOwnerHandleV1 owner,
                                                 BsFfiGrantHandleV1 grant,
                                                 const uint8_t *encoded_ready,
                                                 uintptr_t encoded_ready_length,
                                                 BsFfiGrantEnableResultV1 *out_result);

/**
 * Project the complete enabled-only authoritative file-grant evidence.
 *
 * Grants installed through the legacy host-supplied authorization path are
 * rejected by the service rather than represented as Rust-derived evidence.
 *
 * # Safety
 * `out_evidence` must be writable for one complete v2 evidence structure.
 */
int32_t bs_ffi_grant_evidence_projection_v2(BsFfiServiceHandleV1 service,
                                            BsFfiOwnerHandleV1 owner,
                                            BsFfiGrantHandleV1 grant,
                                            BsFfiFileGrantEvidenceV2 *out_evidence);

/**
 * Return the exact pending grant-outbox record kind and size.
 *
 * # Safety
 * Both scalar outputs must be writable and disjoint.
 */
int32_t bs_ffi_grant_outbound_size_v1(BsFfiServiceHandleV1 service,
                                      BsFfiOwnerHandleV1 owner,
                                      BsFfiGrantHandleV1 grant,
                                      uint32_t *out_record_kind,
                                      uintptr_t *out_length);

/**
 * Copy and consume one exact Ready or receipt; short buffers do not consume.
 *
 * # Safety
 * All output regions must be writable and pairwise disjoint.
 */
int32_t bs_ffi_grant_take_outbound_v1(BsFfiServiceHandleV1 service,
                                      BsFfiOwnerHandleV1 owner,
                                      BsFfiGrantHandleV1 grant,
                                      uint8_t *out_bytes,
                                      uintptr_t out_capacity,
                                      uint32_t *out_record_kind,
                                      uintptr_t *out_length);

/**
 * Non-destructively copy the current exact Ready or receipt and its metadata.
 *
 * A short buffer returns [`BS_FFI_ERR_BUFFER_TOO_SMALL_V1`] after populating
 * `out_metadata`; it never consumes or changes the pending record. A null byte
 * pointer is accepted only when `out_capacity` is zero.
 *
 * # Safety
 * `out_metadata` must be writable. When `out_capacity` is non-zero,
 * `out_bytes` must name that many writable bytes. The output regions must be
 * disjoint.
 */
int32_t bs_ffi_grant_outbound_peek_v2(BsFfiServiceHandleV1 service,
                                      BsFfiOwnerHandleV1 owner,
                                      BsFfiGrantHandleV1 grant,
                                      uint8_t *out_bytes,
                                      uintptr_t out_capacity,
                                      BsFfiGrantOutboundMetadataV2 *out_metadata);

/**
 * Confirm trusted-adapter delivery of only the exact current Ready/receipt.
 *
 * The trusted adapter must call this only after separately recording a Rust
 * peer-accept outcome for the exact bytes. This local assertion does not prove
 * peer provenance, remote attestation, or process-crash recovery.
 *
 * # Safety
 * `confirmation` must be readable and `out_result` writable for their complete
 * structures, and the regions must not overlap.
 */
int32_t bs_ffi_grant_confirm_outbound_delivery_v2(BsFfiServiceHandleV1 service,
                                                  BsFfiOwnerHandleV1 owner,
                                                  BsFfiGrantHandleV1 grant,
                                                  const BsFfiTrustedDeliveryConfirmationInputV2 *confirmation,
                                                  BsFfiTrustedDeliveryConfirmationResultV2 *out_result);

/**
 * Generate a non-zero authority operation id and journal the peer receipt expectation.
 *
 * # Safety
 * `request_digest` must name exactly 32 readable bytes and `out_descriptor`
 * must be writable and disjoint from it.
 */
int32_t bs_ffi_grant_create_outbound_file_descriptor_v1(BsFfiServiceHandleV1 service,
                                                        BsFfiOwnerHandleV1 owner,
                                                        BsFfiGrantHandleV1 grant,
                                                        const uint8_t *request_digest,
                                                        uintptr_t request_digest_length,
                                                        BsFfiFileOperationDescriptorV1 *out_descriptor);

/**
 * Reserve one authenticated inbound descriptor under the sealed target scope.
 *
 * # Safety
 * `descriptor` must be readable and `out_operation` writable; they must not overlap.
 */
int32_t bs_ffi_grant_reserve_inbound_file_operation_v1(BsFfiServiceHandleV1 service,
                                                       BsFfiOwnerHandleV1 owner,
                                                       BsFfiGrantHandleV1 grant,
                                                       const BsFfiFileOperationDescriptorV1 *descriptor,
                                                       BsFfiOperationHandleV1 *out_operation);

/**
 * Consume a reservation before any platform effect may be attempted.
 *
 * # Safety
 * `out_permit` must be writable for one permit handle.
 */
int32_t bs_ffi_grant_mark_file_may_have_started_v1(BsFfiServiceHandleV1 service,
                                                   BsFfiOwnerHandleV1 owner,
                                                   BsFfiGrantHandleV1 grant,
                                                   BsFfiOperationHandleV1 operation,
                                                   BsFfiCommitPermitHandleV1 *out_permit);

/**
 * Finalize a started effect through the factory-sealed durable-file committer.
 *
 * # Safety
 * `effect_digest` must name exactly 32 readable bytes and `out_result` must
 * be writable and disjoint from it.
 */
int32_t bs_ffi_grant_finalize_file_operation_v1(BsFfiServiceHandleV1 service,
                                                BsFfiOwnerHandleV1 owner,
                                                BsFfiGrantHandleV1 grant,
                                                BsFfiCommitPermitHandleV1 permit,
                                                uint32_t outcome,
                                                const uint8_t *effect_digest,
                                                uintptr_t effect_digest_length,
                                                BsFfiFileFinalizationResultV1 *out_result);

/**
 * Retry an unchanged sealed finalization request.
 *
 * # Safety
 * `out_result` must be writable for one finalization result.
 */
int32_t bs_ffi_grant_retry_file_finalization_v1(BsFfiServiceHandleV1 service,
                                                BsFfiOwnerHandleV1 owner,
                                                BsFfiGrantHandleV1 grant,
                                                BsFfiFinalizationRetryHandleV1 retry,
                                                BsFfiFileFinalizationResultV1 *out_result);

/**
 * Cancel a never-started reservation and queue a rejected receipt.
 */
int32_t bs_ffi_grant_cancel_reserved_file_operation_v1(BsFfiServiceHandleV1 service,
                                                       BsFfiOwnerHandleV1 owner,
                                                       BsFfiGrantHandleV1 grant,
                                                       BsFfiOperationHandleV1 operation);

/**
 * Accept an authenticated receipt only for an exact prior expectation.
 *
 * # Safety
 * `encoded_receipt` must be readable and `out_acceptance` writable and disjoint.
 */
int32_t bs_ffi_grant_accept_peer_receipt_v1(BsFfiServiceHandleV1 service,
                                            BsFfiOwnerHandleV1 owner,
                                            BsFfiGrantHandleV1 grant,
                                            const uint8_t *encoded_receipt,
                                            uintptr_t encoded_receipt_length,
                                            uint32_t *out_acceptance);

/**
 * Revoke and release an exact grant only when no security result or linear handle is pending.
 */
int32_t bs_ffi_grant_revoke_v1(BsFfiServiceHandleV1 service,
                               BsFfiOwnerHandleV1 owner,
                               BsFfiGrantHandleV1 grant);

#endif  /* BOUND_SESSION_FFI_V1_H */
