#!/usr/bin/env python3
"""
Generate supplementary table from kernel-level network emulation CSV.

Input:
  Artifacts/network_emulation_kernel_<ARTIFACT_DATE>.csv

Output:
  Docs/supp_tables/s10_kernel_emulation.tex
"""

from __future__ import annotations

import csv
import os
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
ARTIFACTS = ROOT / "Artifacts"
SUPP = ROOT / "Docs" / "supp_tables"

PROFILES = ["mild", "moderate", "severe", "reorder"]
SUITES = ["classic", "pqc_liboqs", "pqc_cryptokit"]
SUITE_LABEL = {
    "classic": "Classic",
    "pqc_liboqs": "liboqs PQC",
    "pqc_cryptokit": "CryptoKit PQC",
}


def _escape_tex(value: str) -> str:
    return (
        value.replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
    )


def _artifact_date_from_env() -> str | None:
    value = os.environ.get("ARTIFACT_DATE") or os.environ.get("SKYBRIDGE_ARTIFACT_DATE")
    if value and value.strip():
        return value.strip()
    return None


def _select_input_csv() -> tuple[str | None, Path | None]:
    date_hint = _artifact_date_from_env()
    if date_hint:
        path = ARTIFACTS / f"network_emulation_kernel_{date_hint}.csv"
        if path.exists():
            return (date_hint, path)
        return (date_hint, None)

    files = sorted(ARTIFACTS.glob("network_emulation_kernel_*.csv"))
    if not files:
        return (None, None)
    path = files[-1]
    suffix = path.stem.replace("network_emulation_kernel_", "", 1)
    return (suffix, path)


def _load_rows(path: Path) -> dict[tuple[str, str, str], dict[str, str]]:
    rows = {}
    with path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            key = (row.get("tool", ""), row.get("profile", ""), row.get("suite", ""))
            rows[key] = row
    return rows


def _fmt_completion(row: dict[str, str] | None) -> str:
    if not row:
        return "-"
    notes = row.get("notes", "")
    if notes.startswith("n/a_dummynet_no_reorder"):
        return r"\textit{n/a}"
    value = row.get("completion", "")
    if not value:
        return "-"
    try:
        return f"{float(value):.4f}"
    except ValueError:
        return _escape_tex(value)


def _fmt_latency(row: dict[str, str] | None, key: str) -> str:
    if not row:
        return "-"
    notes = row.get("notes", "")
    if notes.startswith("n/a_dummynet_no_reorder"):
        return r"\textit{n/a}"
    value = row.get(key, "")
    if not value:
        return "-"
    try:
        return f"{float(value):.1f}"
    except ValueError:
        return _escape_tex(value)


def _write_placeholder() -> Path:
    SUPP.mkdir(parents=True, exist_ok=True)
    out = SUPP / "s10_kernel_emulation.tex"
    out.write_text(
        "\n".join(
            [
                r"\begin{table*}[!tp]",
                r"\centering",
                r"\caption{Supplementary Table \thetable: Kernel-level network emulation cross-check (artifact pending). Run \texttt{Scripts/run\_network\_emulation\_kernel.sh}.}",
                r"\label{tab:supp-kernel-emulation}",
                r"\begin{tabular}{@{}l@{}}",
                r"\toprule",
                r"Artifact data not found. \\",
                r"\bottomrule",
                r"\end{tabular}",
                r"\end{table*}",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    return out


def main() -> None:
    artifact_date, input_csv = _select_input_csv()
    if not input_csv:
        out = _write_placeholder()
        print(f"Wrote placeholder: {out}")
        return

    rows = _load_rows(input_csv)
    SUPP.mkdir(parents=True, exist_ok=True)
    out = SUPP / "s10_kernel_emulation.tex"

    lines: list[str] = []
    lines.append("% Auto-generated by aggregate_kernel_emulation.py")
    lines.append(r"\begin{table*}[!tp]")
    lines.append(r"\centering")
    lines.append(r"\scriptsize")
    lines.append(
        rf"\caption{{Supplementary Table \thetable: Kernel-level network emulation cross-check (shared profiles from \texttt{{Scripts/netem\_profiles.json}}). Common profiles (mild/moderate/severe) are reported for both dummynet and netem when available; reorder is netem-only and marked \textit{{n/a}} for dummynet by design. On some macOS setups, dummynet with localhost endpoint can under-shape absolute delay, so cross-tool interpretation emphasizes completion robustness over millisecond parity unless a non-localhost endpoint is used. Data from \texttt{{Artifacts/network\_emulation\_kernel\_{artifact_date}.csv}}.}}"
    )
    lines.append(r"\label{tab:supp-kernel-emulation}")
    lines.append(r"\setlength{\tabcolsep}{3pt}")
    lines.append(r"\begin{tabular}{@{}llcccccc@{}}")
    lines.append(r"\toprule")
    lines.append(
        r"Profile & Suite & dummynet comp. & dummynet p95 & dummynet p99 & netem comp. & netem p95 & netem p99 \\"
    )
    lines.append(r"\midrule")

    for profile in PROFILES:
        for suite in SUITES:
            dummynet = rows.get(("dummynet", profile, suite))
            netem = rows.get(("netem", profile, suite))
            lines.append(
                " & ".join(
                    [
                        _escape_tex(profile),
                        _escape_tex(SUITE_LABEL.get(suite, suite)),
                        _fmt_completion(dummynet),
                        _fmt_latency(dummynet, "p95"),
                        _fmt_latency(dummynet, "p99"),
                        _fmt_completion(netem),
                        _fmt_latency(netem, "p95"),
                        _fmt_latency(netem, "p99"),
                    ]
                )
                + r" \\"
            )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table*}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote: {out}")


if __name__ == "__main__":
    main()
