#!/usr/bin/env python3
import csv
import json
import math
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from statistics import median


ROOT_DIR = Path(__file__).resolve().parent.parent
ARTIFACTS_DIR = ROOT_DIR / "Artifacts"
GENERATED_DIR = ROOT_DIR / "Docs" / "generated"
EXPECTED_ARTIFACT_DATE = "2026-01-23"
MAX_BATCHES = 5

sys.path.insert(0, str(ROOT_DIR / "Scripts"))
import make_tables  # noqa: E402
from bench_profiles import (
    APPLE_PQC_CONFIG,
    APPLE_XWING_CONFIG,
    CORE_GATE_CONFIGS,
    V2_COMPARE_CONFIGS,
)


_T_CRIT_975 = {
    1: 12.706,
    2: 4.303,
    3: 3.182,
    4: 2.776,
    5: 2.571,
    6: 2.447,
    7: 2.365,
    8: 2.306,
    9: 2.262,
    10: 2.228,
    11: 2.201,
    12: 2.179,
    13: 2.160,
    14: 2.145,
    15: 2.131,
    16: 2.120,
    17: 2.110,
    18: 2.101,
    19: 2.093,
    20: 2.086,
    21: 2.080,
    22: 2.074,
    23: 2.069,
    24: 2.064,
    25: 2.060,
    26: 2.056,
    27: 2.052,
    28: 2.048,
    29: 2.045,
    30: 2.042,
}


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _resolve_artifact_date() -> str:
    value = (
        os.environ.get("ARTIFACT_DATE")
        or os.environ.get("SKYBRIDGE_ARTIFACT_DATE")
        or make_tables._artifact_date_from_main_tex()
        or ""
    ).strip()
    if not value:
        raise SystemExit("ARTIFACT_DATE is required")
    if value != EXPECTED_ARTIFACT_DATE:
        raise SystemExit(
            f"ARTIFACT_DATE must be {EXPECTED_ARTIFACT_DATE}, got {value}"
        )
    return value


def _message_total(msg_sizes: dict, keys: list[str], fallback: int) -> int:
    for key in keys:
        if key in msg_sizes:
            return int(msg_sizes[key].get("total", fallback))
    return int(fallback)


def _assert_configs_exist(data: dict, configs: list[str], label: str) -> None:
    missing = [cfg for cfg in configs if cfg not in data]
    if missing:
        missing_text = ", ".join(missing)
        raise SystemExit(f"Missing {label} configs: {missing_text}")


def _fmt(value: float, digits: int = 3) -> str:
    return f"{value:.{digits}f}"


def _write_macros(macros_path: Path, claims: dict) -> None:
    latency = claims["latency"]
    rtt = claims["rtt"]
    v2 = claims["v2_vs_v1"]
    wire = claims["wire_size_bytes"]
    contrast_latency = claims.get("contrast", {}).get("latency", {})
    contrast_rtt = claims.get("contrast", {}).get("rtt", {})
    core_liboqs = "liboqs PQC (ML-KEM-768 + ML-DSA-65)"
    apple_latency = contrast_latency.get(APPLE_PQC_CONFIG)
    xwing_latency = contrast_latency.get(APPLE_XWING_CONFIG)
    apple_rtt = contrast_rtt.get(APPLE_PQC_CONFIG, {})
    cryptokit_p99 = (
        float(apple_latency["p99"])
        if apple_latency is not None and "p99" in apple_latency
        else float(latency[core_liboqs]["p99"])
    )
    cryptokit_mean = (
        float(apple_latency["mean"])
        if apple_latency is not None and "mean" in apple_latency
        else float(latency[core_liboqs]["mean"])
    )
    cryptokit_p95 = (
        float(apple_latency["p95"])
        if apple_latency is not None and "p95" in apple_latency
        else float(latency[core_liboqs]["p95"])
    )
    cryptokit_rtt_p95 = (
        float(apple_rtt["p95"])
        if "p95" in apple_rtt
        else float(rtt[core_liboqs]["p95"])
    )

    lines = [
        "% Auto-generated by Scripts/collect_claims.py",
        f"% generated_at={claims['generated_at']}",
        f"% artifact_date={claims['artifact_date']}",
        "",
        f"\\newcommand{{\\claimArtifactDate}}{{{claims['artifact_date']}}}",
        f"\\newcommand{{\\claimClassicPNineNineMs}}{{{_fmt(latency['Classic (X25519 + Ed25519)']['p99'])}}}",
        f"\\newcommand{{\\claimLiboqsPNineNineMs}}{{{_fmt(latency['liboqs PQC (ML-KEM-768 + ML-DSA-65)']['p99'])}}}",
        f"\\newcommand{{\\claimLiboqsVTwoPNineNineMs}}{{{_fmt(latency['liboqs PQC v2 FS (ML-KEM-768-FS + ML-DSA-65)']['p99'])}}}",
        f"\\newcommand{{\\claimCryptoKitPNineNineMs}}{{{_fmt(cryptokit_p99)}}}",
        f"\\newcommand{{\\claimClassicMeanMs}}{{{_fmt(latency['Classic (X25519 + Ed25519)']['mean'])}}}",
        f"\\newcommand{{\\claimLiboqsMeanMs}}{{{_fmt(latency['liboqs PQC (ML-KEM-768 + ML-DSA-65)']['mean'])}}}",
        f"\\newcommand{{\\claimLiboqsVTwoMeanMs}}{{{_fmt(latency['liboqs PQC v2 FS (ML-KEM-768-FS + ML-DSA-65)']['mean'])}}}",
        f"\\newcommand{{\\claimCryptoKitMeanMs}}{{{_fmt(cryptokit_mean)}}}",
        f"\\newcommand{{\\claimClassicPNineFiveMs}}{{{_fmt(latency['Classic (X25519 + Ed25519)']['p95'])}}}",
        f"\\newcommand{{\\claimLiboqsPNineFiveMs}}{{{_fmt(latency['liboqs PQC (ML-KEM-768 + ML-DSA-65)']['p95'])}}}",
        f"\\newcommand{{\\claimLiboqsVTwoPNineFiveMs}}{{{_fmt(latency['liboqs PQC v2 FS (ML-KEM-768-FS + ML-DSA-65)']['p95'])}}}",
        f"\\newcommand{{\\claimCryptoKitPNineFiveMs}}{{{_fmt(cryptokit_p95)}}}",
        f"\\newcommand{{\\claimClassicRttPNineFiveMs}}{{{_fmt(rtt['Classic (X25519 + Ed25519)']['p95'])}}}",
        f"\\newcommand{{\\claimLiboqsRttPNineFiveMs}}{{{_fmt(rtt['liboqs PQC (ML-KEM-768 + ML-DSA-65)']['p95'])}}}",
        f"\\newcommand{{\\claimLiboqsVTwoRttPNineFiveMs}}{{{_fmt(rtt['liboqs PQC v2 FS (ML-KEM-768-FS + ML-DSA-65)']['p95'])}}}",
        f"\\newcommand{{\\claimCryptoKitRttPNineFiveMs}}{{{_fmt(cryptokit_rtt_p95)}}}",
        f"\\newcommand{{\\claimClassicPayloadBytes}}{{{wire['classic_payload_handshake']}}}",
        f"\\newcommand{{\\claimLiboqsPayloadBytes}}{{{wire['liboqs_payload_handshake']}}}",
        f"\\newcommand{{\\claimLiboqsVTwoPayloadBytes}}{{{v2['v2_payload_handshake_bytes']}}}",
        f"\\newcommand{{\\claimCryptoKitPayloadBytes}}{{{wire.get('cryptokit_payload_handshake', v2['v2_payload_handshake_bytes'])}}}",
        f"\\newcommand{{\\claimXWingPayloadBytes}}{{{wire.get('xwing_payload_handshake', v2['v2_payload_handshake_bytes'])}}}",
        f"\\newcommand{{\\claimVOnePayloadBytes}}{{{v2['v1_payload_handshake_bytes']}}}",
        f"\\newcommand{{\\claimVTwoPayloadBytes}}{{{v2['v2_payload_handshake_bytes']}}}",
        f"\\newcommand{{\\claimVTwoDeltaPayloadBytes}}{{{v2['delta_payload_handshake_bytes']}}}",
        f"\\newcommand{{\\claimVTwoDeltaMessageABytes}}{{{v2['delta_message_a_bytes']}}}",
        f"\\newcommand{{\\claimVTwoDeltaMessageBBytes}}{{{v2['delta_message_b_bytes']}}}",
        f"\\newcommand{{\\claimVTwoMeanDeltaMs}}{{{_fmt(v2['delta_mean_latency_ms'])}}}",
        f"\\newcommand{{\\claimVTwoPNineFiveDeltaMs}}{{{_fmt(v2['delta_p95_latency_ms'])}}}",
        f"\\newcommand{{\\claimVTwoRttPFiftyDeltaMs}}{{{_fmt(v2['delta_p50_rtt_ms'])}}}",
        f"\\newcommand{{\\claimVTwoRttPNineFiveDeltaMs}}{{{_fmt(v2['delta_p95_rtt_ms'])}}}",
        f"\\newcommand{{\\claimAppleContrastAvailable}}{{{'1' if apple_latency else '0'}}}",
        f"\\newcommand{{\\claimXWingContrastAvailable}}{{{'1' if xwing_latency else '0'}}}",
        "",
    ]
    macros_path.parent.mkdir(parents=True, exist_ok=True)
    macros_path.write_text("\n".join(lines), encoding="utf-8")


def _read_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def _group_complete_batches(rows: list[dict[str, str]], configs: list[str]) -> list[dict[str, dict[str, float]]]:
    required = set(configs)
    filtered = [row for row in rows if row.get("configuration") in required]

    batches: list[dict[str, dict[str, float]]] = []
    current: dict[str, dict[str, float]] = {}
    for row in filtered:
        config = row["configuration"]
        if config in current:
            batches.append(current)
            current = {}
        current[config] = {
            "n": float(row.get("iteration_count", 0) or 0),
            "mean": float(row.get("mean_ms", 0) or 0),
            "std": float(row.get("stddev_ms", 0) or 0),
            "p50": float(row.get("p50_ms", 0) or 0),
            "p95": float(row.get("p95_ms", 0) or 0),
            "p99": float(row.get("p99_ms", 0) or 0),
        }
    if current:
        batches.append(current)

    complete = [batch for batch in batches if required.issubset(set(batch.keys()))]
    return complete[-MAX_BATCHES:]


def _ci95(values: list[float]) -> float:
    n = len(values)
    if n < 2:
        return 0.0
    mu = sum(values) / n
    variance = sum((value - mu) ** 2 for value in values) / (n - 1)
    se = math.sqrt(variance) / math.sqrt(n)
    t = _T_CRIT_975.get(n - 1, 1.96)
    return t * se


def _aggregate_batches(
    batches: list[dict[str, dict[str, float]]], configs: list[str]
) -> tuple[dict[str, dict[str, float]], dict[str, dict[str, object]]]:
    if not batches:
        return {}, {}

    aggregated: dict[str, dict[str, float]] = {}
    batch_values: dict[str, dict[str, object]] = {}
    fields = ("n", "mean", "std", "p50", "p95", "p99")

    for config in configs:
        per_field: dict[str, list[float]] = {field: [] for field in fields}
        for batch in batches:
            values = batch.get(config)
            if not values:
                continue
            for field in fields:
                per_field[field].append(float(values[field]))

        if not per_field["mean"]:
            continue

        aggregated[config] = {
            "n": int(round(median(per_field["n"]))),
            "mean": float(median(per_field["mean"])),
            "std": float(median(per_field["std"])),
            "p50": float(median(per_field["p50"])),
            "p95": float(median(per_field["p95"])),
            "p99": float(median(per_field["p99"])),
        }

        batch_values[config] = {
            "batches": len(per_field["mean"]),
            "mean": per_field["mean"],
            "p95": per_field["p95"],
            "ci95": {
                "mean": _ci95(per_field["mean"]),
                "p95": _ci95(per_field["p95"]),
            },
        }

    return aggregated, batch_values


def main() -> None:
    artifact_date = _resolve_artifact_date()

    latency_csv = make_tables.select_artifact_csv("handshake_bench", artifact_date, strict=True)
    rtt_csv = make_tables.select_artifact_csv("handshake_rtt", artifact_date, strict=True)
    msg_csv = make_tables.select_artifact_csv("message_sizes", artifact_date, strict=True)

    latency_rows = _read_rows(latency_csv)
    rtt_rows = _read_rows(rtt_csv)

    perf_configs = CORE_GATE_CONFIGS
    v2_configs = V2_COMPARE_CONFIGS

    latency_batches = _group_complete_batches(latency_rows, perf_configs)
    rtt_batches = _group_complete_batches(rtt_rows, perf_configs)
    v2_latency_batches = _group_complete_batches(latency_rows, v2_configs)
    v2_rtt_batches = _group_complete_batches(rtt_rows, v2_configs)

    latency, latency_batch_values = _aggregate_batches(latency_batches, perf_configs)
    rtt, rtt_batch_values = _aggregate_batches(rtt_batches, perf_configs)
    v2_latency, v2_latency_batch_values = _aggregate_batches(v2_latency_batches, v2_configs)
    v2_rtt, v2_rtt_batch_values = _aggregate_batches(v2_rtt_batches, v2_configs)

    _assert_configs_exist(latency, perf_configs, "latency")
    _assert_configs_exist(rtt, perf_configs, "rtt")
    _assert_configs_exist(v2_latency, v2_configs, "v2 latency")
    _assert_configs_exist(v2_rtt, v2_configs, "v2 rtt")

    contrast_latency: dict = {}
    contrast_rtt: dict = {}
    contrast_latency_batch_values: dict = {}
    contrast_rtt_batch_values: dict = {}
    contrast_sources: dict[str, str] = {}
    contrast_latency_csv = make_tables.select_artifact_csv("handshake_bench_contrast", artifact_date, strict=False)
    contrast_rtt_csv = make_tables.select_artifact_csv("handshake_rtt_contrast", artifact_date, strict=False)
    if contrast_latency_csv and contrast_rtt_csv:
        contrast_sources["latency_csv"] = str(contrast_latency_csv)
        contrast_sources["rtt_csv"] = str(contrast_rtt_csv)
        contrast_latency_rows = _read_rows(contrast_latency_csv)
        contrast_rtt_rows = _read_rows(contrast_rtt_csv)
        contrast_latency_batches = _group_complete_batches(contrast_latency_rows, [cfg for cfg in [APPLE_PQC_CONFIG] if cfg])
        contrast_rtt_batches = _group_complete_batches(contrast_rtt_rows, [cfg for cfg in [APPLE_PQC_CONFIG] if cfg])
        contrast_latency, contrast_latency_batch_values = _aggregate_batches(contrast_latency_batches, [APPLE_PQC_CONFIG])
        contrast_rtt, contrast_rtt_batch_values = _aggregate_batches(contrast_rtt_batches, [APPLE_PQC_CONFIG])

        xwing_latency_batches = _group_complete_batches(contrast_latency_rows, [APPLE_XWING_CONFIG])
        xwing_rtt_batches = _group_complete_batches(contrast_rtt_rows, [APPLE_XWING_CONFIG])
        xwing_latency, xwing_latency_batch_values = _aggregate_batches(xwing_latency_batches, [APPLE_XWING_CONFIG])
        xwing_rtt, xwing_rtt_batch_values = _aggregate_batches(xwing_rtt_batches, [APPLE_XWING_CONFIG])
        contrast_latency.update(xwing_latency)
        contrast_rtt.update(xwing_rtt)
        contrast_latency_batch_values.update(xwing_latency_batch_values)
        contrast_rtt_batch_values.update(xwing_rtt_batch_values)

    msg_sizes = make_tables.parse_message_sizes(msg_csv)

    finished = _message_total(msg_sizes, ["Finished"], 38)
    classic_a = _message_total(msg_sizes, ["MessageA.Classic"], 293)
    classic_b = _message_total(msg_sizes, ["MessageB.Classic"], 318)
    liboqs_a = _message_total(
        msg_sizes,
        ["MessageA.PQC-liboqs", "MessageA.PQC (liboqs)", "MessageA.PQC"],
        6507,
    )
    liboqs_b = _message_total(
        msg_sizes,
        ["MessageB.PQC-liboqs", "MessageB.PQC (liboqs)", "MessageB.PQC"],
        5419,
    )
    cryptokit_a = _message_total(
        msg_sizes,
        ["MessageA.PQC-CryptoKit", "MessageA.PQC (CryptoKit)", "MessageA.PQC"],
        6507,
    )
    cryptokit_b = _message_total(
        msg_sizes,
        ["MessageB.PQC-CryptoKit", "MessageB.PQC (CryptoKit)", "MessageB.PQC"],
        5419,
    )

    v1_a = _message_total(
        msg_sizes,
        ["MessageA.PQC-liboqs", "MessageA.PQC", "MessageA.PQC-v1"],
        6507,
    )
    v1_b = _message_total(
        msg_sizes,
        ["MessageB.PQC-liboqs", "MessageB.PQC", "MessageB.PQC-v1"],
        5419,
    )
    v2_a = _message_total(
        msg_sizes,
        ["MessageA.PQC-liboqs-v2fs", "MessageA.PQC-v2"],
        v1_a + 34,
    )
    v2_b = _message_total(
        msg_sizes,
        ["MessageB.PQC-liboqs-v2fs", "MessageB.PQC-v2"],
        v1_b + 32,
    )

    v1_cfg = "liboqs PQC (ML-KEM-768 + ML-DSA-65)"
    v2_cfg = "liboqs PQC v2 FS (ML-KEM-768-FS + ML-DSA-65)"

    claims = {
        "artifact_date": artifact_date,
        "generated_at": utc_now(),
        "sources": {
            "latency_csv": str(latency_csv),
            "rtt_csv": str(rtt_csv),
            "message_sizes_csv": str(msg_csv),
            "contrast": contrast_sources,
        },
        "aggregation": {
            "method": "median",
            "max_batches": MAX_BATCHES,
            "latency_batches": len(latency_batches),
            "rtt_batches": len(rtt_batches),
            "v2_latency_batches": len(v2_latency_batches),
            "v2_rtt_batches": len(v2_rtt_batches),
        },
        "batch_values": {
            "latency": latency_batch_values,
            "rtt": rtt_batch_values,
            "v2_latency": v2_latency_batch_values,
            "v2_rtt": v2_rtt_batch_values,
        },
        "latency": latency,
        "rtt": rtt,
        "v2_latency": v2_latency,
        "v2_rtt": v2_rtt,
        "contrast": {
            "available": bool(contrast_latency and contrast_rtt),
            "latency": contrast_latency,
            "rtt": contrast_rtt,
            "batch_values": {
                "latency": contrast_latency_batch_values,
                "rtt": contrast_rtt_batch_values,
            },
        },
        "wire_size_bytes": {
            "finished_frame": finished,
            "classic_payload_handshake": classic_a + classic_b + finished * 2,
            "liboqs_payload_handshake": liboqs_a + liboqs_b + finished * 2,
            "cryptokit_payload_handshake": cryptokit_a + cryptokit_b + finished * 2,
            "xwing_payload_handshake": (
                _message_total(msg_sizes, ["MessageA.XWing"], cryptokit_a)
                + _message_total(msg_sizes, ["MessageB.XWing"], cryptokit_b)
                + finished * 2
            ),
        },
        "v2_vs_v1": {
            "v1_payload_handshake_bytes": v1_a + v1_b + finished * 2,
            "v2_payload_handshake_bytes": v2_a + v2_b + finished * 2,
            "delta_payload_handshake_bytes": (v2_a + v2_b) - (v1_a + v1_b),
            "delta_message_a_bytes": v2_a - v1_a,
            "delta_message_b_bytes": v2_b - v1_b,
            "delta_mean_latency_ms": v2_latency[v2_cfg]["mean"] - v2_latency[v1_cfg]["mean"],
            "delta_p95_latency_ms": v2_latency[v2_cfg]["p95"] - v2_latency[v1_cfg]["p95"],
            "delta_p50_rtt_ms": v2_rtt[v2_cfg]["p50"] - v2_rtt[v1_cfg]["p50"],
            "delta_p95_rtt_ms": v2_rtt[v2_cfg]["p95"] - v2_rtt[v1_cfg]["p95"],
        },
    }
    claims["highlight_metrics"] = {
        "classic_p99_ms": latency["Classic (X25519 + Ed25519)"]["p99"],
        "cryptokit_p99_ms": float(contrast_latency.get(APPLE_PQC_CONFIG, {}).get("p99", latency["liboqs PQC (ML-KEM-768 + ML-DSA-65)"]["p99"])),
        "v2_p95_delta_ms": claims["v2_vs_v1"]["delta_p95_latency_ms"],
    }

    claims_path = ARTIFACTS_DIR / f"claims_{artifact_date}.json"
    claims_path.write_text(
        json.dumps(claims, ensure_ascii=True, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    macros_path = GENERATED_DIR / "claims_macros.tex"
    _write_macros(macros_path, claims)

    print(f"wrote {claims_path}")
    print(f"wrote {macros_path}")


if __name__ == "__main__":
    main()
