#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_spec(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def swift_literal(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return f"\"{value}\""
    if isinstance(value, list):
        return "[" + ", ".join(swift_literal(item) for item in value) + "]"
    raise TypeError(f"Unsupported swift literal: {value!r}")


def csharp_literal(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return f"\"{value}\""
    raise TypeError(f"Unsupported csharp literal: {value!r}")


def emit_swift(spec: dict) -> str:
    layout = spec["layout"]
    materials = spec["materials"]
    motion = spec["motion"]
    typography = spec["typography"]
    palette = spec["palette"]
    navigation = spec["navigation"]

    return f"""// Generated by Scripts/generate_visual_parity_assets.py. Do not edit by hand.
import CoreGraphics
import SwiftUI

public enum VisualParityTokenSet {{
    public enum Layout {{
        public static let captureSize = CGSize(width: {layout["captureWidth"]}, height: {layout["captureHeight"]})
        public static let windowSize = CGSize(width: {layout["windowWidth"]}, height: {layout["windowHeight"]})
        public static let shellOuterMargin: CGFloat = {layout["shellOuterMargin"]}
        public static let shellSurfacePadding: CGFloat = {layout["shellSurfacePadding"]}
        public static let shellCornerRadius: CGFloat = {layout["shellCornerRadius"]}
        public static let sidebarWidth: CGFloat = {layout["sidebarWidth"]}
        public static let sidebarPadding: CGFloat = {layout["sidebarPadding"]}
        public static let sidebarCornerRadius: CGFloat = {layout["sidebarCornerRadius"]}
        public static let topBarHeight: CGFloat = {layout["topBarHeight"]}
        public static let topBarCornerRadius: CGFloat = {layout["topBarCornerRadius"]}
        public static let panelCornerRadius: CGFloat = {layout["panelCornerRadius"]}
        public static let subtlePanelCornerRadius: CGFloat = {layout["subtlePanelCornerRadius"]}
        public static let metricCardCornerRadius: CGFloat = {layout["metricCardCornerRadius"]}
        public static let cardInset: CGFloat = {layout["cardInset"]}
        public static let navButtonCornerRadius: CGFloat = {layout["navButtonCornerRadius"]}
        public static let navButtonHeight: CGFloat = {layout["navButtonHeight"]}
        public static let contentGap: CGFloat = {layout["contentGap"]}
        public static let contentHorizontalPadding: CGFloat = {layout["contentHorizontalPadding"]}
        public static let statusChipHeight: CGFloat = {layout["statusChipHeight"]}
        public static let loginCardWidth: CGFloat = {layout["loginCardWidth"]}
        public static let loginCardCornerRadius: CGFloat = {layout["loginCardCornerRadius"]}
        public static let loginSegmentHeight: CGFloat = {layout["loginSegmentHeight"]}
        public static let buttonHeight: CGFloat = {layout["buttonHeight"]}
        public static let iconButtonSize: CGFloat = {layout["iconButtonSize"]}
    }}

    public enum Materials {{
        public static let defaultGlassOpacity = {materials["defaultGlassOpacity"]}
        public static let defaultBackgroundIntensity = {materials["defaultBackgroundIntensity"]}
        public static let cardFillAlphaDark = {materials["cardFillAlphaDark"]}
        public static let cardFillAlphaLight = {materials["cardFillAlphaLight"]}
        public static let cardStrokeAlpha = {materials["cardStrokeAlpha"]}
        public static let shellSurfaceFillAlphaDark = {materials["shellSurfaceFillAlphaDark"]}
        public static let shellSurfaceFillAlphaLight = {materials["shellSurfaceFillAlphaLight"]}
        public static let shellSurfaceStrokeAlpha = {materials["shellSurfaceStrokeAlpha"]}
        public static let topBarFillAlphaDark = {materials["topBarFillAlphaDark"]}
    }}

    public enum Motion {{
        public static let easeDuration = {motion["easeDuration"]}
        public static let hoverDuration = {motion["hoverDuration"]}
        public static let pressDuration = {motion["pressDuration"]}
        public static let springResponse = {motion["springResponse"]}
        public static let springDampingFraction = {motion["springDampingFraction"]}
    }}

    public enum Typography {{
        public static let heroTitleSize: CGFloat = {typography["heroTitleSize"]}
        public static let sectionTitleSize: CGFloat = {typography["sectionTitleSize"]}
        public static let bodyTextSize: CGFloat = {typography["bodyTextSize"]}
        public static let captionTextSize: CGFloat = {typography["captionTextSize"]}
        public static let navTitleSize: CGFloat = {typography["navTitleSize"]}
        public static let navSubtitleSize: CGFloat = {typography["navSubtitleSize"]}
        public static let pageTitleSize: CGFloat = {typography["pageTitleSize"]}
        public static let pageSubtitleSize: CGFloat = {typography["pageSubtitleSize"]}
        public static let loginHeroTitleSize: CGFloat = {typography["loginHeroTitleSize"]}
        public static let loginSectionTitleSize: CGFloat = {typography["loginSectionTitleSize"]}
        public static let buttonTextSize: CGFloat = {typography["buttonTextSize"]}
    }}

    public enum Navigation {{
        public static let primaryOrder = {swift_literal(navigation["primaryOrder"])}
        public static let secondaryOrder = {swift_literal(navigation["secondaryOrder"])}
    }}

    public enum Palette {{
        public static let windowGradientDark = {swift_literal(palette["windowGradientDark"])}.map(Color.init(hex:))
        public static let windowGradientLight = {swift_literal(palette["windowGradientLight"])}.map(Color.init(hex:))
        public static let sidebarBackground = Color(hex: {swift_literal(palette["sidebarBackground"])})
        public static let shellSurfaceFill = Color(hex: {swift_literal(palette["shellSurfaceFill"])})
        public static let shellSurfaceStroke = Color(hex: {swift_literal(palette["shellSurfaceStroke"])})
        public static let topBarFill = Color(hex: {swift_literal(palette["topBarFill"])})
        public static let panelFillDark = Color(hex: {swift_literal(palette["panelFillDark"])})
        public static let panelFillLight = Color(hex: {swift_literal(palette["panelFillLight"])})
        public static let panelStroke = Color(hex: {swift_literal(palette["panelStroke"])})
        public static let metricCardFillDark = Color(hex: {swift_literal(palette["metricCardFillDark"])})
        public static let metricCardFillLight = Color(hex: {swift_literal(palette["metricCardFillLight"])})
        public static let rowFillDark = Color(hex: {swift_literal(palette["rowFillDark"])})
        public static let loginCardFill = Color(hex: {swift_literal(palette["loginCardFill"])})
        public static let loginCardStroke = Color(hex: {swift_literal(palette["loginCardStroke"])})
        public static let inputFillLight = Color(hex: {swift_literal(palette["inputFillLight"])})
        public static let accent = Color(hex: {swift_literal(palette["accent"])})
        public static let accentPressed = Color(hex: {swift_literal(palette["accentPressed"])})
        public static let success = Color(hex: {swift_literal(palette["success"])})
        public static let warning = Color(hex: {swift_literal(palette["warning"])})
        public static let danger = Color(hex: {swift_literal(palette["danger"])})
        public static let textPrimaryDark = Color(hex: {swift_literal(palette["textPrimaryDark"])})
        public static let textSecondaryDark = Color(hex: {swift_literal(palette["textSecondaryDark"])})
        public static let textMutedDark = Color(hex: {swift_literal(palette["textMutedDark"])})
        public static let textPrimaryLight = Color(hex: {swift_literal(palette["textPrimaryLight"])})
        public static let textSecondaryLight = Color(hex: {swift_literal(palette["textSecondaryLight"])})
        public static let textMutedLight = Color(hex: {swift_literal(palette["textMutedLight"])})
        public static let selectedNavFill = Color(hex: {swift_literal(palette["selectedNavFill"])})
        public static let selectedNavIndicator = Color(hex: {swift_literal(palette["selectedNavIndicator"])})
    }}
}}

private extension Color {{
    init(hex: String) {{
        let sanitized = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        let value = UInt64(sanitized, radix: 16) ?? 0
        let a, r, g, b: UInt64
        switch sanitized.count {{
        case 8:
            a = (value & 0xFF00_0000) >> 24
            r = (value & 0x00FF_0000) >> 16
            g = (value & 0x0000_FF00) >> 8
            b = value & 0x0000_00FF
        case 6:
            a = 0xFF
            r = (value & 0xFF00_00) >> 16
            g = (value & 0x00FF_00) >> 8
            b = value & 0x0000_FF
        default:
            a = 0xFF
            r = 0
            g = 0
            b = 0
        }}

        self.init(
            .sRGB,
            red: Double(r) / 255.0,
            green: Double(g) / 255.0,
            blue: Double(b) / 255.0,
            opacity: Double(a) / 255.0
        )
    }}
}}
"""


def emit_csharp(spec: dict) -> str:
    layout = spec["layout"]
    materials = spec["materials"]
    motion = spec["motion"]
    typography = spec["typography"]
    palette = spec["palette"]
    navigation = spec["navigation"]

    lines = [
        "// Generated by Scripts/generate_visual_parity_assets.py. Do not edit by hand.",
        "namespace Skybridge.WinClient.VisualParity;",
        "",
        "internal static class GeneratedVisualParity",
        "{",
        "    internal static class Layout",
        "    {",
    ]
    for key, value in layout.items():
        name = "".join(part.capitalize() for part in key.split("_")) if "_" in key else key[0].upper() + key[1:]
        lines.append(f"        public const double {name} = {csharp_literal(value)};")
    lines += [
        "    }",
        "",
        "    internal static class Materials",
        "    {",
    ]
    for key, value in materials.items():
        name = "".join(part.capitalize() for part in key.split("_")) if "_" in key else key[0].upper() + key[1:]
        lines.append(f"        public const double {name} = {csharp_literal(value)};")
    lines += [
        "    }",
        "",
        "    internal static class Motion",
        "    {",
    ]
    for key, value in motion.items():
        name = "".join(part.capitalize() for part in key.split("_")) if "_" in key else key[0].upper() + key[1:]
        lines.append(f"        public const double {name} = {csharp_literal(value)};")
    lines += [
        "    }",
        "",
        "    internal static class Typography",
        "    {",
    ]
    for key, value in typography.items():
        name = "".join(part.capitalize() for part in key.split("_")) if "_" in key else key[0].upper() + key[1:]
        lines.append(f"        public const double {name} = {csharp_literal(value)};")
    lines += [
        "    }",
        "",
        "    internal static class Palette",
        "    {",
    ]
    for key, value in palette.items():
        name = "".join(part.capitalize() for part in key.split("_")) if "_" in key else key[0].upper() + key[1:]
        if isinstance(value, list):
            joined = ", ".join(f"\"{item}\"" for item in value)
            lines.append(f"        public static readonly string[] {name} = new[] {{ {joined} }};")
        else:
            lines.append(f"        public const string {name} = {csharp_literal(value)};")
    lines += [
        "    }",
        "",
        "    internal static class Navigation",
        "    {",
        f"        public static readonly string[] PrimaryOrder = new[] {{ {', '.join(csharp_literal(v) for v in navigation['primaryOrder'])} }};",
        f"        public static readonly string[] SecondaryOrder = new[] {{ {', '.join(csharp_literal(v) for v in navigation['secondaryOrder'])} }};",
        "    }",
        "}",
    ]
    return "\n".join(lines)


def emit_xaml(spec: dict) -> str:
    layout = spec["layout"]
    typography = spec["typography"]
    palette = spec["palette"]
    materials = spec["materials"]

    def stop_line(color: str, offset: float) -> str:
        return f'            <GradientStop Color="{color}" Offset="{offset}" />'

    dark_stops = "\n".join(
        stop_line(color, offset)
        for color, offset in zip(palette["windowGradientDark"], [0, 0.52, 1])
    )
    light_stops = "\n".join(
        stop_line(color, offset)
        for color, offset in zip(palette["windowGradientLight"], [0, 1])
    )

    return f"""<!-- Generated by Scripts/generate_visual_parity_assets.py. Do not edit by hand. -->
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <x:Double x:Key="ParityCaptureWidth">{layout["captureWidth"]}</x:Double>
    <x:Double x:Key="ParityCaptureHeight">{layout["captureHeight"]}</x:Double>
    <x:Double x:Key="ParityWindowWidth">{layout["windowWidth"]}</x:Double>
    <x:Double x:Key="ParityWindowHeight">{layout["windowHeight"]}</x:Double>
    <x:Double x:Key="ParityShellOuterMargin">{layout["shellOuterMargin"]}</x:Double>
    <x:Double x:Key="ParityShellSurfacePadding">{layout["shellSurfacePadding"]}</x:Double>
    <x:Double x:Key="ParitySidebarWidth">{layout["sidebarWidth"]}</x:Double>
    <x:Double x:Key="ParitySidebarPadding">{layout["sidebarPadding"]}</x:Double>
    <x:Double x:Key="ParityTopBarHeight">{layout["topBarHeight"]}</x:Double>
    <x:Double x:Key="ParityIconButtonSize">{layout["iconButtonSize"]}</x:Double>
    <x:Double x:Key="ParityNavButtonHeight">{layout["navButtonHeight"]}</x:Double>
    <x:Double x:Key="ParityButtonHeight">{layout["buttonHeight"]}</x:Double>
    <x:Double x:Key="ParityLoginSegmentHeight">{layout["loginSegmentHeight"]}</x:Double>
    <x:Double x:Key="ParityStatusChipHeight">{layout["statusChipHeight"]}</x:Double>
    <x:Double x:Key="ParityTopBarFillAlphaDark">{materials["topBarFillAlphaDark"]}</x:Double>
    <x:Double x:Key="ParityHeroTitleSize">{typography["heroTitleSize"]}</x:Double>
    <x:Double x:Key="ParitySectionTitleSize">{typography["sectionTitleSize"]}</x:Double>
    <x:Double x:Key="ParityBodyTextSize">{typography["bodyTextSize"]}</x:Double>
    <x:Double x:Key="ParityCaptionTextSize">{typography["captionTextSize"]}</x:Double>
    <x:Double x:Key="ParityNavTitleSize">{typography["navTitleSize"]}</x:Double>
    <x:Double x:Key="ParityNavSubtitleSize">{typography["navSubtitleSize"]}</x:Double>
    <x:Double x:Key="ParityPageTitleSize">{typography["pageTitleSize"]}</x:Double>
    <x:Double x:Key="ParityPageSubtitleSize">{typography["pageSubtitleSize"]}</x:Double>
    <x:Double x:Key="ParityLoginHeroTitleSize">{typography["loginHeroTitleSize"]}</x:Double>
    <x:Double x:Key="ParityLoginSectionTitleSize">{typography["loginSectionTitleSize"]}</x:Double>
    <x:Double x:Key="ParityButtonTextSize">{typography["buttonTextSize"]}</x:Double>

    <CornerRadius x:Key="ParityShellCornerRadius">{layout["shellCornerRadius"]}</CornerRadius>
    <CornerRadius x:Key="ParitySidebarCornerRadius">{layout["sidebarCornerRadius"]}</CornerRadius>
    <CornerRadius x:Key="ParityTopBarCornerRadius">{layout["topBarCornerRadius"]}</CornerRadius>
    <CornerRadius x:Key="ParityPanelCornerRadius">{layout["panelCornerRadius"]}</CornerRadius>
    <CornerRadius x:Key="ParitySubtlePanelCornerRadius">{layout["subtlePanelCornerRadius"]}</CornerRadius>
    <CornerRadius x:Key="ParityMetricCardCornerRadius">{layout["metricCardCornerRadius"]}</CornerRadius>
    <CornerRadius x:Key="ParityNavButtonCornerRadius">{layout["navButtonCornerRadius"]}</CornerRadius>
    <CornerRadius x:Key="ParityLoginCardCornerRadius">{layout["loginCardCornerRadius"]}</CornerRadius>
    <CornerRadius x:Key="ParityChipCornerRadius">{layout["chipCornerRadius"]}</CornerRadius>

    <LinearGradientBrush x:Key="ParityWindowBackgroundBrush" StartPoint="0,0" EndPoint="1,1">
{dark_stops}
    </LinearGradientBrush>
    <LinearGradientBrush x:Key="ParityLoginBackgroundBrush" StartPoint="0,0" EndPoint="0,1">
{light_stops}
    </LinearGradientBrush>

    <SolidColorBrush x:Key="ParitySidebarBackgroundBrush" Color="{palette["sidebarBackground"]}" />
    <SolidColorBrush x:Key="ParityShellSurfaceBrush" Color="{palette["shellSurfaceFill"]}" />
    <SolidColorBrush x:Key="ParityShellSurfaceStrokeBrush" Color="{palette["shellSurfaceStroke"]}" />
    <SolidColorBrush x:Key="ParityTopBarBrush" Color="{palette["topBarFill"]}" />
    <SolidColorBrush x:Key="ParityPanelBrush" Color="{palette["panelFillDark"]}" />
    <SolidColorBrush x:Key="ParityPanelLightBrush" Color="{palette["panelFillLight"]}" />
    <SolidColorBrush x:Key="ParityPanelStrokeBrush" Color="{palette["panelStroke"]}" />
    <SolidColorBrush x:Key="ParityMetricCardBrush" Color="{palette["metricCardFillDark"]}" />
    <SolidColorBrush x:Key="ParityMetricCardLightBrush" Color="{palette["metricCardFillLight"]}" />
    <SolidColorBrush x:Key="ParityRowBrush" Color="{palette["rowFillDark"]}" />
    <SolidColorBrush x:Key="ParityLoginCardBrush" Color="{palette["loginCardFill"]}" />
    <SolidColorBrush x:Key="ParityLoginCardStrokeBrush" Color="{palette["loginCardStroke"]}" />
    <SolidColorBrush x:Key="ParityInputFillLightBrush" Color="{palette["inputFillLight"]}" />
    <SolidColorBrush x:Key="ParityAccentBrush" Color="{palette["accent"]}" />
    <SolidColorBrush x:Key="ParityAccentPressedBrush" Color="{palette["accentPressed"]}" />
    <SolidColorBrush x:Key="ParitySuccessBrush" Color="{palette["success"]}" />
    <SolidColorBrush x:Key="ParityWarningBrush" Color="{palette["warning"]}" />
    <SolidColorBrush x:Key="ParityDangerBrush" Color="{palette["danger"]}" />
    <SolidColorBrush x:Key="ParityTextPrimaryDarkBrush" Color="{palette["textPrimaryDark"]}" />
    <SolidColorBrush x:Key="ParityTextSecondaryDarkBrush" Color="{palette["textSecondaryDark"]}" />
    <SolidColorBrush x:Key="ParityTextMutedDarkBrush" Color="{palette["textMutedDark"]}" />
    <SolidColorBrush x:Key="ParityTextPrimaryLightBrush" Color="{palette["textPrimaryLight"]}" />
    <SolidColorBrush x:Key="ParityTextSecondaryLightBrush" Color="{palette["textSecondaryLight"]}" />
    <SolidColorBrush x:Key="ParityTextMutedLightBrush" Color="{palette["textMutedLight"]}" />
    <SolidColorBrush x:Key="ParitySelectedNavBrush" Color="{palette["selectedNavFill"]}" />
    <SolidColorBrush x:Key="ParitySelectedNavIndicatorBrush" Color="{palette["selectedNavIndicator"]}" />

    <SolidColorBrush x:Key="PrimaryBrush" Color="{palette["accent"]}" />
    <SolidColorBrush x:Key="PrimaryBrushPressed" Color="{palette["accentPressed"]}" />
    <SolidColorBrush x:Key="PrimaryForegroundBrush" Color="#FFFFFFFF" />
    <SolidColorBrush x:Key="ShellBackgroundBrush" Color="#00000000" />
    <SolidColorBrush x:Key="ShellCardBrush" Color="{palette["panelFillDark"]}" />
    <SolidColorBrush x:Key="ShellCardElevatedBrush" Color="{palette["metricCardFillDark"]}" />
    <SolidColorBrush x:Key="ShellCardSubtleBrush" Color="{palette["panelFillLight"]}" />
    <SolidColorBrush x:Key="ShellStrokeBrush" Color="{palette["panelStroke"]}" />
    <SolidColorBrush x:Key="ShellStrokeStrongBrush" Color="{palette["shellSurfaceStroke"]}" />
    <SolidColorBrush x:Key="ShellTextPrimaryBrush" Color="{palette["textPrimaryDark"]}" />
    <SolidColorBrush x:Key="ShellTextSecondaryBrush" Color="{palette["textSecondaryDark"]}" />
    <SolidColorBrush x:Key="ShellTextMutedBrush" Color="{palette["textMutedDark"]}" />
    <SolidColorBrush x:Key="ShellSuccessBrush" Color="{palette["success"]}" />
    <SolidColorBrush x:Key="ShellWarningBrush" Color="{palette["warning"]}" />
    <SolidColorBrush x:Key="ShellDangerBrush" Color="{palette["danger"]}" />

    <Style x:Key="ShellHeroTitleStyle" TargetType="TextBlock">
        <Setter Property="Foreground" Value="{{StaticResource ShellTextPrimaryBrush}}" />
        <Setter Property="FontFamily" Value="Segoe UI Variable Display" />
        <Setter Property="FontSize" Value="{{StaticResource ParityHeroTitleSize}}" />
        <Setter Property="FontWeight" Value="SemiBold" />
    </Style>
    <Style x:Key="ShellSectionTitleStyle" TargetType="TextBlock">
        <Setter Property="Foreground" Value="{{StaticResource ShellTextPrimaryBrush}}" />
        <Setter Property="FontFamily" Value="Segoe UI Variable Text" />
        <Setter Property="FontSize" Value="{{StaticResource ParitySectionTitleSize}}" />
        <Setter Property="FontWeight" Value="SemiBold" />
    </Style>
    <Style x:Key="ShellBodyTextStyle" TargetType="TextBlock">
        <Setter Property="Foreground" Value="{{StaticResource ShellTextSecondaryBrush}}" />
        <Setter Property="FontFamily" Value="Segoe UI Variable Text" />
        <Setter Property="FontSize" Value="{{StaticResource ParityBodyTextSize}}" />
        <Setter Property="TextWrapping" Value="WrapWholeWords" />
    </Style>
    <Style x:Key="ShellCaptionTextStyle" TargetType="TextBlock">
        <Setter Property="Foreground" Value="{{StaticResource ShellTextMutedBrush}}" />
        <Setter Property="FontFamily" Value="Segoe UI Variable Text" />
        <Setter Property="FontSize" Value="{{StaticResource ParityCaptionTextSize}}" />
    </Style>
    <Style x:Key="ShellPanelStyle" TargetType="Border">
        <Setter Property="Background" Value="{{StaticResource ParityPanelBrush}}" />
        <Setter Property="BorderBrush" Value="{{StaticResource ParityPanelStrokeBrush}}" />
        <Setter Property="BorderThickness" Value="1" />
        <Setter Property="CornerRadius" Value="{{StaticResource ParityPanelCornerRadius}}" />
    </Style>
    <Style x:Key="ShellPanelSubtleStyle" TargetType="Border">
        <Setter Property="Background" Value="{{StaticResource ParityPanelLightBrush}}" />
        <Setter Property="BorderBrush" Value="{{StaticResource ParityPanelStrokeBrush}}" />
        <Setter Property="BorderThickness" Value="1" />
        <Setter Property="CornerRadius" Value="{{StaticResource ParitySubtlePanelCornerRadius}}" />
    </Style>
    <Style x:Key="ShellMetricCardStyle" TargetType="Border">
        <Setter Property="Background" Value="{{StaticResource ParityMetricCardBrush}}" />
        <Setter Property="BorderBrush" Value="{{StaticResource ParityPanelStrokeBrush}}" />
        <Setter Property="BorderThickness" Value="1" />
        <Setter Property="CornerRadius" Value="{{StaticResource ParityMetricCardCornerRadius}}" />
        <Setter Property="Padding" Value="18" />
    </Style>
    <Style x:Key="ShellTextInputStyle" TargetType="Control">
        <Setter Property="Foreground" Value="{{StaticResource ShellTextPrimaryBrush}}" />
        <Setter Property="Background" Value="{{StaticResource ParityPanelLightBrush}}" />
        <Setter Property="BorderBrush" Value="{{StaticResource ParityPanelStrokeBrush}}" />
        <Setter Property="BorderThickness" Value="1" />
    </Style>
    <Style x:Key="AccentButtonStyle" TargetType="Button">
        <Setter Property="Background" Value="{{StaticResource PrimaryBrush}}" />
        <Setter Property="Foreground" Value="{{StaticResource PrimaryForegroundBrush}}" />
        <Setter Property="BorderThickness" Value="0" />
        <Setter Property="CornerRadius" Value="14" />
        <Setter Property="Padding" Value="18,0" />
        <Setter Property="Height" Value="{{StaticResource ParityButtonHeight}}" />
        <Setter Property="MinHeight" Value="{{StaticResource ParityButtonHeight}}" />
        <Setter Property="FontWeight" Value="SemiBold" />
        <Setter Property="FontSize" Value="{{StaticResource ParityButtonTextSize}}" />
    </Style>
    <Style x:Key="IconButton" TargetType="Button">
        <Setter Property="Background" Value="{{StaticResource ParityPanelBrush}}" />
        <Setter Property="Foreground" Value="{{StaticResource ShellTextPrimaryBrush}}" />
        <Setter Property="BorderBrush" Value="{{StaticResource ParityPanelStrokeBrush}}" />
        <Setter Property="BorderThickness" Value="1" />
        <Setter Property="CornerRadius" Value="12" />
        <Setter Property="Width" Value="{{StaticResource ParityIconButtonSize}}" />
        <Setter Property="Height" Value="{{StaticResource ParityIconButtonSize}}" />
        <Setter Property="Padding" Value="0" />
    </Style>
    <Style x:Key="ShellSecondaryButtonStyle" TargetType="Button" BasedOn="{{StaticResource AccentButtonStyle}}">
        <Setter Property="Background" Value="{{StaticResource ParityPanelLightBrush}}" />
        <Setter Property="BorderThickness" Value="1" />
        <Setter Property="BorderBrush" Value="{{StaticResource ParityPanelStrokeBrush}}" />
        <Setter Property="Foreground" Value="{{StaticResource ShellTextPrimaryBrush}}" />
    </Style>
</ResourceDictionary>
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--spec",
        type=Path,
        default=Path("Docs/mac-baseline/ui-baseline/visual-spec.json"),
    )
    parser.add_argument(
        "--swift-out",
        type=Path,
        default=Path("Sources/SkyBridgeVisualParity/GeneratedVisualParity.swift"),
    )
    parser.add_argument(
        "--windows-cs-out",
        type=Path,
        required=True,
    )
    parser.add_argument(
        "--windows-xaml-out",
        type=Path,
        required=True,
    )
    args = parser.parse_args()

    spec = load_spec(args.spec)
    write_text(args.swift_out, emit_swift(spec))
    write_text(args.windows_cs_out, emit_csharp(spec))
    write_text(args.windows_xaml_out, emit_xaml(spec))


if __name__ == "__main__":
    main()
