/*
 * skybridge_ffi.h — C ABI for the SkyBridge portable secure-transport core.
 *
 * GENERATED by cbindgen from crates/skybridge-ffi. Do not edit by hand.
 *
 * This is the language-agnostic surface that lets non-Rust clients
 * (Windows C#/.NET via P/Invoke, C/C++, Linux) drive the same SkyBridge
 * protocol/handshake/policy/discovery core the Apple apps use, instead of
 * each platform reimplementing the protocol.
 *
 * Memory & threading contract:
 *   - All handles are opaque; create with the matching *_new/_create call and
 *     release exactly once with the matching *_free call. Double-free is UB.
 *   - Functions returning `SkyBridgeBuffer` transfer ownership of the buffer to
 *     the caller; release it with `skybridge_buffer_free`.
 *   - Callbacks may be invoked from a background thread. They must be
 *     re-entrancy-safe and must not call back into the same client handle.
 *   - No Rust panic ever crosses the boundary; failures are reported via
 *     `SkyBridgeStatus` return codes.
 */


#ifndef SKYBRIDGE_FFI_H
#define SKYBRIDGE_FFI_H

/* WARNING: generated file — edits will be overwritten by the build. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Stable integer encoding of [`skybridge_core::DowngradePolicy`] for the C ABI.
 */
enum SkyBridgeDowngradePolicy
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Strict PQC, compliance: classic fallback is *never* allowed.
     */
    SKY_BRIDGE_DOWNGRADE_POLICY_STRICT_PQC_COMPLIANCE = 0,
    /**
     * Strict PQC, bootstrap-assisted: one-time classic control channel only.
     */
    SKY_BRIDGE_DOWNGRADE_POLICY_STRICT_PQC_BOOTSTRAP_ASSISTED = 1,
    /**
     * Prefer PQC, allow eligible + rate-limited classic business fallback.
     */
    SKY_BRIDGE_DOWNGRADE_POLICY_PREFER_PQC = 2,
    /**
     * Default posture: no mandatory initial PQC attempt; same fallback gating.
     */
    SKY_BRIDGE_DOWNGRADE_POLICY_DEFAULT = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum SkyBridgeDowngradePolicy SkyBridgeDowngradePolicy;
#else
typedef uint32_t SkyBridgeDowngradePolicy;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Stable integer encoding of [`skybridge_core::FallbackReason`] for the C ABI.
 */
enum SkyBridgeFallbackReason
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * ALLOWED: no usable PQC provider/suite is available locally.
     */
    SKY_BRIDGE_FALLBACK_REASON_PQC_PROVIDER_UNAVAILABLE = 0,
    /**
     * ALLOWED: PQC suite negotiation produced no mutually supported suite.
     */
    SKY_BRIDGE_FALLBACK_REASON_SUITE_NEGOTIATION_FAILED = 1,
    /**
     * BLOCKED: network-derived timeout (never downgrade-eligible).
     */
    SKY_BRIDGE_FALLBACK_REASON_TIMEOUT = 2,
    /**
     * BLOCKED: peer signature failed to verify.
     */
    SKY_BRIDGE_FALLBACK_REASON_SIGNATURE_VERIFICATION_FAILED = 3,
    /**
     * BLOCKED: replay / anti-rollback detection tripped.
     */
    SKY_BRIDGE_FALLBACK_REASON_REPLAY_DETECTED = 4,
    /**
     * BLOCKED: key confirmation (FINISHED MAC) failed.
     */
    SKY_BRIDGE_FALLBACK_REASON_KEY_CONFIRMATION_FAILED = 5,
    /**
     * BLOCKED: peer identity did not match the pinned/enrolled identity.
     */
    SKY_BRIDGE_FALLBACK_REASON_IDENTITY_MISMATCH = 6,
    /**
     * BLOCKED: signed suite list did not match the negotiated suite.
     */
    SKY_BRIDGE_FALLBACK_REASON_SUITE_SIGNATURE_MISMATCH = 7,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum SkyBridgeFallbackReason SkyBridgeFallbackReason;
#else
typedef uint32_t SkyBridgeFallbackReason;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Kind discriminant passed to a [`SkyBridgeEventCallback`].
 */
enum SkyBridgeEventKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * A discovery scan produced a fresh snapshot. `payload` is the
     * `NearbyDiscoverySnapshot` serialized as JSON (UTF-8).
     */
    SKY_BRIDGE_EVENT_KIND_DISCOVERY_SNAPSHOT = 0,
    /**
     * Handshake state changed. `payload` is a small JSON object.
     */
    SKY_BRIDGE_EVENT_KIND_HANDSHAKE_STATE = 1,
    /**
     * A downgrade decision was made. `payload` is the decision serialized as
     * JSON (the `DowngradeEvent` for an authorized downgrade, or a typed denial).
     */
    SKY_BRIDGE_EVENT_KIND_DOWNGRADE_EVENT = 2,
    /**
     * Discovery stopped (either by request or because the scan window ended).
     * `payload` is empty.
     */
    SKY_BRIDGE_EVENT_KIND_DISCOVERY_STOPPED = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum SkyBridgeEventKind SkyBridgeEventKind;
#else
typedef uint32_t SkyBridgeEventKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Opaque top-level client handle. Owns a crate-private multi-thread Tokio
 * runtime used to drive async core operations (currently the live mDNS
 * discovery browse) and the registered event callback.
 */
typedef struct SkyBridgeClient SkyBridgeClient;

/**
 * Opaque handle wrapping a generated PQC device identity
 * ([`skybridge_core::RustPqcIdentityMaterial`]): ML-DSA-65 signing keypair plus
 * ML-KEM-768 and X-Wing KEM keypairs.
 */
typedef struct SkyBridgeIdentity SkyBridgeIdentity;

/**
 * Opaque handle wrapping a [`skybridge_core::PolicyGate`] — the single
 * authority that authorizes or denies a PQC→Classic downgrade for a peer,
 * applying the reason whitelist, policy posture, and per-peer 300s cooldown.
 */
typedef struct SkyBridgePolicyGate SkyBridgePolicyGate;

/**
 * A heap-allocated, length-prefixed byte buffer handed to the caller.
 *
 * `ptr`/`len`/`cap` together describe a `Vec<u8>` that Rust forgot; the caller
 * MUST return it via [`skybridge_buffer_free`] exactly once. A buffer with a
 * NULL `ptr` and zero `len` is the canonical "empty/none" value.
 */
typedef struct {
    /**
     * Pointer to the first byte, or NULL when empty.
     */
    uint8_t *ptr;
    /**
     * Number of valid bytes.
     */
    uintptr_t len;
    /**
     * Allocation capacity (needed to reconstruct the `Vec` for freeing).
     */
    uintptr_t cap;
} SkyBridgeBuffer;

/**
 * C function pointer invoked for asynchronous events.
 *
 * * `user_data` — the opaque pointer registered alongside the callback.
 * * `kind` — which event this is.
 * * `payload` / `payload_len` — a borrowed, *callback-lifetime* byte view
 *   (typically UTF-8 JSON). The pointer is only valid for the duration of the
 *   call; copy what you need. May be NULL with `payload_len == 0`.
 *
 * The callback may be invoked from a background thread; it must be
 * re-entrancy-safe and must not call back into the same client handle.
 */
typedef void (*SkyBridgeEventCallback)(void *user_data,
                                       SkyBridgeEventKind kind,
                                       const uint8_t *payload,
                                       uintptr_t payload_len);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free a [`SkyBridgeBuffer`] previously returned by this library. Safe to call
 * with an empty (NULL `ptr`) buffer. After the call the buffer's fields are
 * reset to the empty state; do not use the pointer again.
 *
 * # Safety
 * `buffer` must point to a `SkyBridgeBuffer` this library produced and that has
 * not already been freed.
 */
int32_t skybridge_buffer_free(SkyBridgeBuffer *buffer);

/**
 * ABI/library version string (`env!("CARGO_PKG_VERSION")`), NUL-terminated,
 * static. Do **not** free it.
 */
const char *skybridge_version(void);

/**
 * Generate a fresh PQC device identity. On success writes an owned handle to
 * `*out_identity`; free it with [`skybridge_identity_free`].
 *
 * # Safety
 * `out_identity` must be a valid, writable pointer.
 */
int32_t skybridge_identity_generate(SkyBridgeIdentity **out_identity);

/**
 * Copy the ML-DSA-65 signing public key into `*out_buffer` (caller frees with
 * [`skybridge_buffer_free`]).
 *
 * # Safety
 * `identity` must be a live handle; `out_buffer` must be writable.
 */
int32_t skybridge_identity_signing_public_key(const SkyBridgeIdentity *identity,
                                              SkyBridgeBuffer *out_buffer);

/**
 * Copy the ML-KEM-768 KEM public key into `*out_buffer`.
 *
 * # Safety
 * `identity` must be a live handle; `out_buffer` must be writable.
 */
int32_t skybridge_identity_mlkem768_public_key(const SkyBridgeIdentity *identity,
                                               SkyBridgeBuffer *out_buffer);

/**
 * Copy the X-Wing hybrid KEM public key into `*out_buffer`.
 *
 * # Safety
 * `identity` must be a live handle; `out_buffer` must be writable.
 */
int32_t skybridge_identity_xwing_public_key(const SkyBridgeIdentity *identity,
                                            SkyBridgeBuffer *out_buffer);

/**
 * Free an identity handle. Safe to call with NULL.
 *
 * # Safety
 * `identity` must be a handle produced by this library and not already freed.
 */
int32_t skybridge_identity_free(SkyBridgeIdentity *identity);

/**
 * Create a policy gate with the given downgrade posture and the canonical
 * 300s per-peer cooldown. On success writes a handle to `*out_gate`.
 *
 * # Safety
 * `out_gate` must be writable.
 */
int32_t skybridge_policy_gate_new(SkyBridgeDowngradePolicy policy, SkyBridgePolicyGate **out_gate);

/**
 * Variant of [`skybridge_policy_gate_new`] taking the policy as a raw `u32`
 * (the [`SkyBridgeDowngradePolicy`] code) for callers that pass plain integers.
 *
 * # Safety
 * `out_gate` must be writable.
 */
int32_t skybridge_policy_gate_new_code(uint32_t policy_code, SkyBridgePolicyGate **out_gate);

/**
 * Read the configured downgrade policy posture back as a [`SkyBridgeDowngradePolicy`]
 * code written to `*out_policy_code`.
 *
 * # Safety
 * `gate` must be live; `out_policy_code` must be writable.
 */
int32_t skybridge_policy_gate_policy(const SkyBridgePolicyGate *gate, uint32_t *out_policy_code);

/**
 * Ask the gate to authorize a PQC→Classic downgrade for `peer`.
 *
 * * `peer_ptr`/`peer_len` — UTF-8 peer identifier (stable, not a network
 *   locator). Must be valid UTF-8.
 * * `from_suite_wire` / `to_suite_wire` — wire ids of the PQC suite attempted
 *   and the Classic suite to downgrade to.
 * * `reason` — the failure reason being evaluated.
 * * `transcript_ptr`/`transcript_len` — optional transcript-hash anchor
 *   (pass NULL/0 for none).
 * * `out_decision_json` — receives the decision serialized as JSON (the
 *   `DowngradeEvent` when authorized, otherwise a `{ "denied": ... }` object).
 *   Caller frees with [`skybridge_buffer_free`].
 *
 * Returns [`SkyBridgeStatus::OK`] when the downgrade is **authorized**, and
 * [`SkyBridgeStatus::DOWNGRADE_DENIED`] when it is denied (still writing the
 * JSON explaining why). Both are normal outcomes.
 *
 * # Safety
 * `gate` must be a live, mutable handle; the byte pointers must satisfy the
 * `(ptr, len)` contract; `out_decision_json` must be writable.
 */
int32_t skybridge_policy_gate_authorize_downgrade(SkyBridgePolicyGate *gate,
                                                  const uint8_t *peer_ptr,
                                                  uintptr_t peer_len,
                                                  uint16_t from_suite_wire,
                                                  uint16_t to_suite_wire,
                                                  SkyBridgeFallbackReason reason,
                                                  const uint8_t *transcript_ptr,
                                                  uintptr_t transcript_len,
                                                  SkyBridgeBuffer *out_decision_json);

/**
 * Variant of [`skybridge_policy_gate_authorize_downgrade`] taking the reason as
 * a raw `u32` ([`SkyBridgeFallbackReason`] code).
 *
 * # Safety
 * Same contract as [`skybridge_policy_gate_authorize_downgrade`].
 */
int32_t skybridge_policy_gate_authorize_downgrade_code(SkyBridgePolicyGate *gate,
                                                       const uint8_t *peer_ptr,
                                                       uintptr_t peer_len,
                                                       uint16_t from_suite_wire,
                                                       uint16_t to_suite_wire,
                                                       uint32_t reason_code,
                                                       const uint8_t *transcript_ptr,
                                                       uintptr_t transcript_len,
                                                       SkyBridgeBuffer *out_decision_json);

/**
 * Free a policy-gate handle. Safe to call with NULL.
 *
 * # Safety
 * `gate` must be a handle produced by this library and not already freed.
 */
int32_t skybridge_policy_gate_free(SkyBridgePolicyGate *gate);

/**
 * Create a client handle. On success writes a handle to `*out_client`; free it
 * with [`skybridge_client_free`].
 *
 * # Safety
 * `out_client` must be writable.
 */
int32_t skybridge_client_new(SkyBridgeClient **out_client);

/**
 * Register (or clear) the event callback for this client.
 *
 * Pass a NULL `callback` to clear the previously registered sink. `user_data`
 * is passed back verbatim on every callback invocation. The callback may fire
 * from a background thread (see [`SkyBridgeEventCallback`]).
 *
 * # Safety
 * `client` must be live. The `callback` (if non-NULL) and `user_data` must
 * remain valid until they are cleared or the client is freed.
 */
int32_t skybridge_client_set_event_callback(SkyBridgeClient *client,
                                            SkyBridgeEventCallback callback,
                                            void *user_data);

/**
 * Start a live mDNS discovery browse of `_skybridge._tcp` for `duration_ms`.
 *
 * Runs on the client's Tokio runtime in the background. When the browse window
 * elapses, the resolved peers are projected into a `NearbyDiscoverySnapshot`
 * and delivered to the registered callback as a
 * [`SkyBridgeEventKind::DiscoverySnapshot`] (JSON payload), followed by a
 * [`SkyBridgeEventKind::DiscoveryStopped`]. Returns
 * [`SkyBridgeStatus::INVALID_STATE`] if a browse is already running.
 *
 * # Safety
 * `client` must be a live handle.
 */
int32_t skybridge_client_start_discovery(SkyBridgeClient *client, uint64_t duration_ms);

/**
 * Signal that no further discovery should be considered active for this client.
 *
 * The in-flight browse is bounded by its own window and cannot be hard-killed
 * mid-flight, so this clears the "running" flag (allowing a new browse to be
 * started) rather than aborting the OS-level mDNS socket. Idempotent.
 *
 * # Safety
 * `client` must be a live handle.
 */
int32_t skybridge_client_stop_discovery(SkyBridgeClient *client);

/**
 * Whether a discovery browse is currently in flight. Writes 0/1 to `*out_running`.
 *
 * # Safety
 * `client` must be live; `out_running` must be writable.
 */
int32_t skybridge_client_discovery_running(const SkyBridgeClient *client, bool *out_running);

/**
 * Free a client handle (and shut down its runtime). Safe to call with NULL.
 *
 * # Safety
 * `client` must be a handle produced by this library and not already freed. Any
 * registered callback must not be used after this call.
 */
int32_t skybridge_client_free(SkyBridgeClient *client);

/**
 * Encode a file-transfer OFFER frame (`SBF1`) into `*out_buffer`.
 *
 * * `transfer_id_ptr` — exactly 16 bytes.
 * * `expected_sha256_ptr` — exactly 32 bytes.
 * * `filename_ptr`/`filename_len` — UTF-8 filename (1..=255 bytes, no NUL).
 *
 * # Safety
 * All `(ptr, len)` pairs must satisfy their length contracts; `out_buffer`
 * must be writable.
 */
int32_t skybridge_file_frame_encode_offer(const uint8_t *transfer_id_ptr,
                                          uint64_t total_size,
                                          uint32_t chunk_size,
                                          const uint8_t *expected_sha256_ptr,
                                          const uint8_t *filename_ptr,
                                          uintptr_t filename_len,
                                          SkyBridgeBuffer *out_buffer);

/**
 * Encode a file-transfer CHUNK frame into `*out_buffer`.
 *
 * # Safety
 * `transfer_id_ptr` must point to 16 bytes; the payload `(ptr, len)` pair must
 * be valid; `out_buffer` must be writable.
 */
int32_t skybridge_file_frame_encode_chunk(const uint8_t *transfer_id_ptr,
                                          uint32_t sequence,
                                          const uint8_t *payload_ptr,
                                          uintptr_t payload_len,
                                          SkyBridgeBuffer *out_buffer);

/**
 * Encode a file-transfer RECEIPT frame into `*out_buffer`.
 *
 * # Safety
 * `transfer_id_ptr` must point to 16 bytes; `computed_sha256_ptr` to 32 bytes;
 * the reason `(ptr, len)` pair must be valid UTF-8; `out_buffer` must be
 * writable.
 */
int32_t skybridge_file_frame_encode_receipt(const uint8_t *transfer_id_ptr,
                                            bool ok,
                                            const uint8_t *computed_sha256_ptr,
                                            const uint8_t *reason_ptr,
                                            uintptr_t reason_len,
                                            SkyBridgeBuffer *out_buffer);

/**
 * Encode a file-transfer CHUNK-ACK frame into `*out_buffer`. (Cannot fail
 * except on a NULL transfer id or out buffer.)
 *
 * # Safety
 * `transfer_id_ptr` must point to 16 bytes; `out_buffer` must be writable.
 */
int32_t skybridge_file_frame_encode_chunk_ack(const uint8_t *transfer_id_ptr,
                                              uint32_t acked_through_seq,
                                              SkyBridgeBuffer *out_buffer);

/**
 * Returns `true` (written to `*out_is_file_frame`) if `(ptr, len)` looks like a
 * binary file frame (vs a JSON keepalive).
 *
 * # Safety
 * The `(ptr, len)` pair must be valid; `out_is_file_frame` must be writable.
 */
int32_t skybridge_file_frame_is_file_frame(const uint8_t *plaintext_ptr,
                                           uintptr_t plaintext_len,
                                           bool *out_is_file_frame);

/**
 * Decode a file-transfer frame into a JSON description written to
 * `*out_json` (caller frees with [`skybridge_buffer_free`]).
 *
 * The JSON is a tagged object, e.g.
 * `{"type":"chunk","transfer_id":"<hex>","sequence":0,"payload_len":4}`.
 * Binary payloads are base64-encoded under `payload_base64` for the chunk type.
 * Returns [`SkyBridgeStatus::INVALID_ARGUMENT`] on a malformed frame.
 *
 * # Safety
 * The `(ptr, len)` pair must be valid; `out_json` must be writable.
 */
int32_t skybridge_file_frame_decode(const uint8_t *plaintext_ptr,
                                    uintptr_t plaintext_len,
                                    SkyBridgeBuffer *out_json);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SKYBRIDGE_FFI_H */
