name: macos-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode and Swift versions
        run: |
          xcodebuild -version
          swift --version

      - name: Generate .icns if AppIcon.png exists
        run: |
          bash scripts/generate-app-icon.sh || true

      - name: Build SkyBridgeCompassApp (SPM)
        working-directory: macos/SkyBridgeCompassApp
        run: |
          swift build --product SkyBridgeCompassApp -c release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SkyBridgeCompassApp-release
          path: macos/SkyBridgeCompassApp/.build/**